### ISSUE TITLE
Include type 1 fonts in CTAN distribution

### ISSUE THREAD

**Issue by thomas001** [khaledhosny/libertinus#10]
Using autoinst [1] it is quite easy to generate type 1 fonts from otf fonts in various encodings. I use type 1 versions of libertine serif for quite some time without problems. It would be nice to see them included in the official package, though. Using fontspec and luatex is not always an option.

[1] https://www.ctan.org/pkg/fontools

**Comment by khaledhosny** [comment]
Maintaining Type 1 fonts and TeX support files is not something I’m looking forward to do. It might be relatively easy for text fonts, but for math it is just unworkable for me, and since this project started for doing a math font people will naturally ask for math support as well.
