### ISSUE TITLE
Support MUFI character recommendation

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#101]
The MUFI group published a recommendation for the selection of characters from the Unicode Standard and for characters to be allocated to the Private Use Area (PUA), they are suitable to be implemented in Cormorant fonts. See:
https://folk.uib.no/hnooh/mufi/specs/index.html
Alternatively, you can add more OT features to achieve similar implementations.

**Comment by khaledhosny** [comment]
Out of scope.
