### ISSUE TITLE
Support in Ten­nent's libertine package

### ISSUE THREAD

**Issue by pank** [khaledhosny/libertinus#11]
Hi Khaled,

Thanks for all your efforts!  

I usually use the [libertine](https://www.ctan.org/tex-archive/fonts/libertine) package for my LaTeX documents and it's pretty great.  Do you think it would make sense to either adapt some of the features of that package or, maybe better, ask Bob Tennent if he would be willing to add support for libertinus (in `xetex`/`luatex)?

Thanks,
Rasmus

**Comment by khaledhosny** [comment]
What features of the LaTeX package you think are useful to borrow? As for Bob Tennent using LIbertinus, that is his call and I think you will have to ask him.

**Comment by pank** [comment]
Khaled Hosny <notifications@github.com> writes:

> What features of the LaTeX package you think are useful to borrow?

For the purpose of an otf font, it's a wrapper around fontspec.  It
provides handy ways to switch between numbers (osf, linings etc.), to
scale the monospaced font, and provides macros to switch to a particular
font (say "Libertine Display").  Everything can be done with fontspec as
well, but it requires more configuration.

> As for Bob Tennent using LIbertinus, that is his call and I think you
> will have to ask him.

I'm happy to ask him, but I did not want to do so without asking here
first as it is your work.

Thanks,
Rasmus

-- 
ツ

**Comment by khaledhosny** [comment]
Great, so nothing for me to do for now.
