### ISSUE TITLE
Blackboard bold N

### ISSUE THREAD

**Issue by Bolpat** [khaledhosny/libertinus#110]
The letter ℕ (Unicode U+2115) has a space after the glyph. Especially in ℕ₀, the space is very unappealing. This has been the case in Libertine, too.

**Comment by khaledhosny** [comment]
Thanks for the report, should be fixed now!

**Comment by Bolpat** [comment]
Wow! That was fast. Thank you very much.

**Comment by Bolpat** [comment]
I really don't wanna complain, but did you just forget fixing it in libertinusserifdisplay-regular.otf?

**Comment by khaledhosny** [comment]
Should be fixed now as well.
