### ISSUE TITLE
Degree Celsius/Fahrenheit signs not bolded in Libertinus Serif Bold Italic

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#115]
Degree Celsius and Degree Fahrenheit signs looks the same in Libertinus Serif Italic and Libertinus Serif Bold Italic.

See: #112

**Comment by mgavioli** [comment]
Also: Serif Semibold °C and °F same are Bold.

Scale from the main 'C' and 'F' to the letter part of '°C' and '°F' is also variable:

Serif | °C / C | °F / F
--------|----------|--------
Regular | 92.8% | 93%
Italic | 89.2% | 89%
S.bold | 85.2% | 89.2%
S.bold it. | 88.3% | 89%
Bold | 89.2% | 89.1%
Bold it. | 89.2% | 89%

There is a cluster near 89%, but also some odd balls. While consistency across fonts is probably not very important, consistency within each font is preferable; see for instance Semi-bold. With a font grid of 1000 FU, 0.1% is 10 FU, i.e. the magnitude of the curve overshoot => not really negligeable.
