### ISSUE TITLE
Problem with stacking diacritics in Italics

### ISSUE THREAD

**Issue by dajare** [khaledhosny/libertinus#118]
Fairly regularly in my work I need to use stacking diacritics. Here is a sample string:

    bərēšīṯ bå̄rå̄ʾ ʾɛ̆lōhīm ʾēṯ haššå̄mayim wəʾēṯ hå̄ʾå̄rɛṣ

With regular upright text (*not* the way these transliterations are typically presented), the _[macron][m]_ and _[overring][o]_ above the /a/ behave just fine (showing Brill for comparison):

![regular][1]

However, typically these transliterations use _italics_, and the "stacking" disappears:

![italics][2]

Can the behaviour of the upright font be extended also to the italics? I live in hope.

Samples produced using LibreOffice Writer, Version: 5.4.2.2; Build ID: 1:5.4.2-0ubuntu0.17.10.1.

---

**Update**: And just for info, here's two more well-behaved examples:

![another screenshot][3]

I'm actually surprised Cambria passes this wee test!

[1]: https://i.imgur.com/NNBNS0M.png
[2]: https://i.imgur.com/Lwcla5h.png
[3]: https://i.imgur.com/0OZaPCa.png
[o]: https://en.wikipedia.org/wiki/Ring_(diacritic)#Overring
[m]: https://en.wikipedia.org/wiki/Macron_(diacritic)

**Comment by tuffnatty** [comment]
I would say that the macron above ring is shifted right too much in the upright font as well.

**Comment by mgavioli** [comment]
I have prepared a [Pull Request](https://github.com/khaledhosny/libertinus/pull/126) hopefully fixing the issue described here (aring + combining macron).

If there are more 'stacked combinations' needing a fix, please detail them.
