### ISSUE TITLE
Support Bitcoin sign

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#119]
It would be awesome if you add support for Bitcoin (₿) sign.

**Comment by waldyrious** [comment]
Reference links:
- https://unicode-table.com/en/20BF/
- http://www.fileformat.info/info/unicode/char/20BF/

also, you misspelled "Bitcoin" as "Bitcion" in the issue title :)

**Comment by KrasnayaPloshchad** [comment]
OK, I fixed it.
