### ISSUE TITLE
\frac within \sqrt

### ISSUE THREAD

**Issue by oldman77** [khaledhosny/libertinus#12]
First of all thanks for your great work, Khaled!

I encountered the following issue concerning Libertinus Math: Using \frac within a \sqrt results in typesetting a root only spanning the numerator as well in XeLaTeX as in LuaLaTeX (Linux, Mac OS X and Windows 10; using most recent versions of each provided by TeX Live 2015).

oldman77

**Comment by khaledhosny** [comment]
A test file would be great to see what is the exact issue.

**Comment by oldman77** [comment]
This is my mwe.
`\documentclass{article}
\usepackage{unicode-math}
\setmainfont{Libertinus Serif}
\setmathfont{Libertinus Math}
\begin{document}
\[
\sqrt{\frac{a}{b}}
\]
\end{document}
`

**Comment by alerque** [comment]
@oldman77 If you enter multiple lines of code and then select them later and hit the "insert code" button in the toolbar it will show you how to do a fenced code block where newlines will be preserved. If you start with nothing or a single line selected it  defaults to the inline code mode which can't have line breaks.

The basic syntax is like this:

    ```
    code line 1
    code line 2
    ```

**Comment by khaledhosny** [comment]
Hmm, looks like I don’t have big radicals at all, I guess I never drew them.

PS. I fixed the code listing.

**Comment by oldman77** [comment]
Thanks for your support guys!
