### ISSUE TITLE
\Vert too big in LaTeX

### ISSUE THREAD

**Issue by wrtc90** [khaledhosny/libertinus#120]
When using libertinus math font, the `\Vert` symbol seems too big. Example code:

```tex
% !TeX program = lualatex
\documentclass{scrartcl}

\usepackage{mathtools}
\usepackage{amssymb}

\usepackage{unicode-math}
\usepackage{fontspec}
    \setmainfont{Libertinus Serif}
    \setsansfont{Libertinus Sans}
    \setmathfont{Libertinus Math}

\usepackage[main=ngerman,english]{babel}

% macros for underscores of vectors
\newcommand{\ubar}[1]{\mkern 1.5mu\underline{\mkern-1.5mu#1\mkern-1.5mu}\mkern 1.5mu}
\newcommand{\uubar}[1]{\ubar{\ubar{#1}}}

% macros for bold symbols of vectors
\renewcommand{\vec}[1]{\symbf{#1}}
\newcommand{\vvec}[1]{\ubar{\symbfup{#1}}}
\newcommand{\norm}[1]{\left\lVert#1\right\rVert}

\begin{document}

    \begin{align}
        y &= \norm{\vvec{r}_{\vec{\sigma}}(\vvec{\sigma}_{n+1,j+1})}
    \end{align}

\end{document}
```

**Comment by alerque** [comment]
For the benefit of anybody like myself following this but _not_ familiar with math typesetting and curious about this report, here is a comparison with the above sample code rendered in _Libertinus Math_ vs. _Asana Math_:

![selection_458](https://user-images.githubusercontent.com/173595/35765445-dafba8fa-08d4-11e8-98ac-9d43622f4fb1.png)
![selection_459](https://user-images.githubusercontent.com/173595/35765446-e1a01a6a-08d4-11e8-99c3-3b2e129aa6ac.png)

**Comment by wrtc90** [comment]
I don't see any difference with the sizes of the \Vert:

![sample kopie](https://user-images.githubusercontent.com/16955343/36864310-959fe556-1d8c-11e8-8cf8-4dd64dfad0df.jpeg)

Me being blind, no change intended or installation/configuration mistake on my part?

**Comment by khaledhosny** [comment]
The vertical bars are now sized just like parenthesis, so at least we are consistent.
