### ISSUE TITLE
Braces too small in math mode using autosizing

### ISSUE THREAD

**Issue by wrtc90** [khaledhosny/libertinus#121]
All of the braces seem to small when using autosizing in LaTeX, as they do not reach over the top of the content:

![image](https://user-images.githubusercontent.com/16955343/35766613-e7414118-08db-11e8-9ee0-010fbe65298c.png)

As a sidenote, this is even worse with XITS Math. Here's the output using legacy math fonts:

![image](https://user-images.githubusercontent.com/16955343/35766639-1cb2a152-08dc-11e8-8a0f-16b1041acd84.png)

And as always, a MWE:

```
% !TeX program = lualatex
\documentclass{scrartcl}

\usepackage{mathtools}
\usepackage{amssymb}

\usepackage{unicode-math}
\usepackage{fontspec}
    \setmainfont{Libertinus Serif}
    \setsansfont{Libertinus Sans}

\usepackage[main=ngerman,english]{babel}

\begin{document}

	\setmathfont{Libertinus Math}
    \begin{align}
        \left(\frac{1}{2} \right) > \left[ \frac{1}{3} \right] > \left\lbrace \frac{1}{3} \right\rbrace
    \end{align}

\end{document}
```

**Comment by wrtc90** [comment]
Could you elaborate on why this request is invalid? Are you unable to reproduce it or is this a design choice?

**Comment by khaledhosny** [comment]
This a normal behavior, in TeX delimiters don’t cover exactly their contents. It just happens to do so with Computer Modern in these examples, but for other content it would behave differently. See https://groups.google.com/d/msg/comp.text.tex/18-1r1JJoz0/To6lRbbrKMcJ

**Comment by wrtc90** [comment]
Indeed, the braces are off in some cases for Computer Modern too. Thanks for the explanation and the great work on this font.
