### ISSUE TITLE
Add optical size

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#123]
With this feature the font will make the character presented scaling, for example, while 1 scaled very small as the same appearence of the character ₁, then its shape will be a bit bold as ₁. 
![Illustration](https://user-images.githubusercontent.com/10364351/36111476-383bf568-1061-11e8-8789-ae1aa44b518a.PNG)
There are two ways to get support:
1. Add `size` feature tag
2. Add `opsz` axis tag

**Comment by KrasnayaPloshchad** [comment]
> 2. Add opsz axis tag

To make it works, you have to convert the font into CFF2 and TrueType formats.

**Comment by khaledhosny** [comment]
Same thing as #56.

**Comment by genodeftest** [comment]
I am getting many warnings when using libertinus with lualatex:

	LaTeX Font Warning: Font shape `U/wasy/m/n' in size <9.59447> not available
	(Font)              size <10> substituted on input line 31.

are those related?

**Comment by khaledhosny** [comment]
I don’t think so.
