### ISSUE TITLE
LineMetrics not correct in Java

### ISSUE THREAD

**Issue by gsssbjo** [khaledhosny/libertinus#124]
Hi,

This can be a Java issue but I'm getting incorrect line metrics for _Libertinus Serif_ and _Libertinus Math_ fonts in Java platform. Here is a snippet:

```
Font font=new Font("Libertinus Serif",Font.PLAIN,12);
LineMetrics lm=font.getLineMetrics("Aqj", g2d.getFontRenderContext());
System.out.println("lm.height="+lm.getHeight());
System.out.println("lm.ascent="+lm.getAscent());
System.out.println("lm.descent="+lm.getDescent());
```

This code returns negative descent:
```
lm.height=11.993408
lm.ascent=10.020493
lm.descent=-4.0597687
```

Libertinus Math returns higher values than the actual ascent, descent:

```
lm.height=29.863586
lm.ascent=17.462402
lm.descent=12.401184
```

**Comment by khaledhosny** [comment]
I have no idea from where Java is polling these data, there are several places in OpenType fonts where line metrics are stored and applications don’t always agree on how to interpret them, however the values in the fonts are sensible as far as I can tell.
