### ISSUE TITLE
Add "Linux Libertine" and "Linux Libertine O" identical to "Libertinus Serif"

### ISSUE THREAD

**Issue by kiwi0fruit** [khaledhosny/libertinus#127]
I've read OFL text and at first I thought that you can actually use "Linux Libertine Math" font name. But now I'm not sure about meaning of the word "use"... But anyway You cannot use "Linux Libertine" reserved name that is given in quotes at the beginning of the file as a font family name. In order to use to it you need to obtain written permission from Philipp H. Poll. I guess he would not mind giving such permission if you (or somebody else interested in) would ask him.

**Comment by alerque** [comment]
Why? The "Linux" name was always a ridiculous misnomer, and at this point I think this project & name have established themselves enough that there is nothing to be gained (and possibly things to be lost) from trying to switch the name back to the project it was forked from.

**Comment by kiwi0fruit** [comment]
Two quite similar projects with different names is bad. Here is an example of css from Wikipedia page:
```css
.mw-body h1, .mw-body-content h1, .mw-body-content h2 {
    font-family: 'Linux Libertine','Georgia','Times',serif;
    ...
}
```
If Libertinus Serif was next version of Linux Libertine then Wikipedia (and all other sites who use Linux Libertine) would use it (together with future patches) instead of old 2012, unpatched Linux Libertine. And actually most of the new sites that shoose this font would add "Linux Libertine" instead of "Libertinus Serif" to css.

Actually it's quite optional request and it's doesn't really matter - css in the web mostly such a mess...

**Comment by fred-wang** [comment]
@kiwi0fruit See also issue #16

**Comment by fitojb** [comment]
Re: @kiwi0fruit’s comment: [I mentioned that very issue](https://phabricator.wikimedia.org/T74515#1875631) back in 2015 to MediaWiki maintainers.

**Comment by kiwi0fruit** [comment]
@fitojb You said that Philipp Poll, is MIA. So he didn't respond to questions about using Linux Libertine name? Or may be the connect attempts were poor?

**Comment by kiwi0fruit** [comment]
@fred-wang Actually if there would be a person who contact with Philipp Poll and get a permission to use the name - then it would not matter what name Khaled Hosny would prefer: automatic renaming in FontForge is a matter of a short python script. So that there would be two identical fonts but with different names.

The probem is only in contacting with Philipp Poll and geting a permission. And finding the person who want's to do it.

**Comment by kiwi0fruit** [comment]
@fitojb Oh. I've noticed problem with Linux Libertine O / Linux Libertine - two fonts with different names... Also a problem.

As a hack - we actually can use "Linux Libertine O" for a fork name - it's not a reserved name due to LL OFL. But this does not solve the problems with using LL in css...

May be it's actually better to use Libertinus Serif everywhere.

**Comment by kiwi0fruit** [comment]
I've written a PM and also opened discussion about permission:
https://sourceforge.net/p/linuxlibertine/discussion/307868/thread/38e13cd3/

**Comment by alerque** [comment]
@kiwi0fruit Dude slow down. You're making assumptions about a mile a minute, and not all of them make sense. Also it's worth noting that the reason this fork got started was to fix the bugs because the original developer was unresponsive. It's been 4+ years with no response from him. If you have some contact method _other than_ the SF project discussion that's one thing, but at this point you are rehashing things everybody has already been over almost ad-nauseum.

**Comment by kiwi0fruit** [comment]
There is only one thing you are right: no other ways of contacting author
except FontForge.

19 февр. 2018 г. 22:45 пользователь "Caleb Maclennan" <
notifications@github.com> написал:

**Comment by fred-wang** [comment]
@kiwi0fruit Thanks for contacting Philipp... I guess you checked the SF forum and you saw that some comments are still waiting for replies/moderation? And that actually Philipp has not been active on SF for 4 years ( https://sourceforge.net/u/philthelion/profile/ ) ?

I suggest to close this issue and #128 until we get explicit request from Philipp / MathJax that some actions are needed on the Libertinus side.

**Comment by kiwi0fruit** [comment]
@fred-wang I also thought about closing it until response from Phillip...

But there's one thing left to think of: does Phillip has right to give us permission we need. After all Linux is a registered trademark.

**Comment by kiwi0fruit** [comment]
@fred-wang when I was on Source Forge I noticed that there is no topic about granting permission. And I also noted that in my newly created account default settings prevent me from receiving PM. Only notifications for issues and such.
So I see that it seems like he wasn't contacted about permissions :)

**Comment by kiwi0fruit** [comment]
[This document](https://www.linuxfoundation.org/trademark-usage/) says that `Incorrect: <The Linux Foundation mark> <your product name>`. But what about names like "Linux Mint"?

**Comment by fred-wang** [comment]
@kiwi0fruit Can you please continue this discussion on Linux Libertinus sourceforge forum? Thanks!

**Comment by kiwi0fruit** [comment]
That was the wrong document. The right one is [this one](https://www.linuxmark.org/programs/legal/trademark/sublicense-agreement). Quote: "Authorized Good/Services" means Linux­-based goods/services. Linux­-based goods are computer systems and software using, incorporating or derived from any version of the Linux kernel...

Other uses seem to be "fair use". It seems to me that naming a font is not a fair use... So in order to name a font Linux Libertine we might need to get Linus Torvalds permission... I guess I ask him after Phillip response :D

**Comment by davelab6** [comment]
I think you are misreading the ofl terms; rfn restrictions apply "in whole
or in part"

**Comment by kiwi0fruit** [comment]
Nope. Resticted Font Names have no connection to "in whole or in part".

Anyway it's not important anymore. I'm overwhelmed with number of problems that arise when you want legally use Linux Libertine font name. The more I think about the more I think it should be dropped for good.

**Comment by davelab6** [comment]
I agree it should be dropped for good :)

http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#60735680


Question: 5.4 Am I not allowed to use any part of the Reserved Font Names?

Answer: You may not use individual words from the Reserved Font Names

**Comment by KrasnayaPloshchad** [comment]
Phillip moved his website to here:
https://libertine-fonts.org/
This site is rewritten by WordPress, each article has comment board at the below. Maybe we can get response if we leave comment in there.

**Comment by kiwi0fruit** [comment]
If we luckily get Phillip response should we then ask Linus? %)

20 февр. 2018 г. 22:37 пользователь "Krasnaya Ploshchad’" <
notifications@github.com> написал:

**Comment by alerque** [comment]
Well huh, that's interesting. No motion on SF yet, but from the font sample generator and other usage on the website it looks like the original author is planning a rename anyway to drop the "Linux". That kind of makes _this issue_ a moot point. The original name is going away both on the original and this fork. I guess the question becomes:

* are they going to bring in all the fixes from Libertinus
* and then continue actively engaging community contributions to improve

or

* will Libertinus continue to be the better font?

Until there is **significant** evidence and momentum to the contrary my money is on the latter and I don't think there is anything to do on this side of things yet.

**Comment by KrasnayaPloshchad** [comment]
@kiwi0fruit You can try to write an user style to do it.

**Comment by KrasnayaPloshchad** [comment]
This can also be achieved by writing an extension. On AMO website I found [MathML-fonts](https://addons.mozilla.org/firefox/addon/mathml-fonts/) extension recently. The structure is very simple, just including a CSS file and two fonts, the CSS file only include `@font-face` rules. So that’s not a hard work to do.

**Comment by kiwi0fruit** [comment]
What can be achieved actually?

**Comment by KrasnayaPloshchad** [comment]
The following codes can replacing Linux Libertine by Libertinus Serif when you input into [Stylus](https://addons.mozilla.org/firefox/addon/styl-us/):
```
@-moz-document url-prefix(http://), url-prefix("https://")
{

@font-face {
    font-family: Linux Libertine;
    src: local('Libertinus Serif');
}

@font-face {
    font-family: Linux Libertine O;
    src: local('Libertinus Serif');
}

}
```
If you want to write an extension for Firefox, you can use [Extension source viewer](https://addons.mozilla.org/firefox/addon/crxviewer/) to see the source of MathML-fonts, then you can try to write your own extension to do that, and install it via about:debugging page.

**Comment by KrasnayaPloshchad** [comment]
I suggest discussing at forum.userstyles.org.

**Comment by kiwi0fruit** [comment]
I'm aware of this possibility: https://github.com/kiwi0fruit/open-fonts#stylebot

**Comment by KrasnayaPloshchad** [comment]
If you want to intergrate Libertinus via extension, you should better converting font files into WOFF(2) format.

**Comment by KrasnayaPloshchad** [comment]
On Windows you can copy the following codes from here, save as XXX.reg file, then double-click this file to merge into system, finally it would works with some web browsers:
```
﻿Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"Linux Biolinum"="Libertinus Sans"
"Linux Biolinum Keyboard"="Libertinus Keyboard"
"Linux Libertine"="Libertinus Serif"
"Linux Libertine Display"="Libertinus Serif Display"
"Linux Libertine Initials"="Libertinus Serif Initials"
"Linux Libertine Mono"="Libertinus Mono"
```
It’s interesting to know how to do it in macOS and Linux. Additionaly, if you are using LibreOffice, you have to write replace table in Tools -> Options -> Fonts while necessary.

**Comment by kiwi0fruit** [comment]
Nice to know it can be done.

ср, 27 июня 2018, 0:20 Krasnaya Ploshchad’ <notifications@github.com>:

**Comment by KrasnayaPloshchad** [comment]
> Additionaly, if you are using LibreOffice, you have to write replace table in Tools -> Options -> Fonts while necessary.

LibreOffice has a request to load Windows registry for font substitution, it would be nice if this is implemented.
https://bugs.documentfoundation.org/show_bug.cgi?id=113007
