### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by kiwi0fruit** [khaledhosny/libertinus#128]
https://github.com/mathjax/MathJax/issues/1932

**Comment by alerque** [comment]
This doesn't really identify an issue. Can you edit and elaborate on what would need to be done to _Libertinus Math_ to support MathJax?

**Comment by kiwi0fruit** [comment]
There should be found a person who wants to add Libertinus Serif to MathJax.

Actually MathJax needs some kind of tuning to support a font (as I read
it's because JavaScript can't read font metrics).

19 февр. 2018 г. 18:55 пользователь "Caleb Maclennan" <
notifications@github.com> написал:

**Comment by fred-wang** [comment]
Libertinus contains all the necessary font data for text and math layout, it's up to the MathJax project to properly use these data and/or adapt the fonts somehow (as they do for other open source fonts). Libertinus is under OFL and the name is not reserved ( https://github.com/khaledhosny/libertinus/blob/master/OFL.txt ) so someone from the MathJax community can easily do whatever is needed. I don't think this requires any action by the Libertinus developers.

**Comment by kiwi0fruit** [comment]
@fred-wang I agree that it would be much easier for someone from MathJax community to adapt the font. And the only way this issue is useful here is that somebody from Libertinus developers see and decide that it's a good idea to add Libertinus to MathJax (and then actually add it). But I'm pessimistic about that...

**Comment by fred-wang** [comment]
@kiwi0fruit I don't see why Libertinus developers should decide whether something is good or bad for MathJax and even less do the work to integrate it into MathJax. This is up to MathJax's community. As I said, the font is under OFL and the name is not reserved, so they can do whatever they want without asking permission.

**Comment by kiwi0fruit** [comment]
Maybe because they want it? I see only this reason. But I doubt it would
happen. But they may want if they want.

19 февр. 2018 г. 23:46 пользователь "Frédéric Wang" <
notifications@github.com> написал:

**Comment by fred-wang** [comment]
@kiwi0fruit Well, even if some Libertinus developer is happy to do the job, the actual work has to happen in the MathJax repo, not the Libertinus one. So I don't see any reason to keep this issue opened.

**Comment by khaledhosny** [comment]
What @fred-wang, this needs to be done in MathJax as the format and support files it needs are specific to it.
