### ISSUE TITLE
Some fonts are encoded as UnicodeBMP and some (with no need?)  as Unicode Full

### ISSUE THREAD

**Issue by mgavioli** [khaledhosny/libertinus#130]
Some of the fonts are encoded as Unicode BMP and some as Unicode Full, even if no glyph is mapped in the non-BMP planes.

For the serif fonts:
Regular: Full
Italic: BMP
Semi-bold: BMP
Semi-bols italic: Full
Bold: BMP
Bold italic: Full

Is there a reason for this?

**Comment by khaledhosny** [comment]
It does not have any practical differences, it just control what characters FontForge views by default in font view, BMP should be enough for all fonts except ones that have characters from other planes (like the math font).
