### ISSUE TITLE
ſj (long s + j) ligature

### ISSUE THREAD

**Issue by nloveladyallen** [khaledhosny/libertinus#140]
The ſj (long s + j) pair lacks a ligature, and looks awful. Here’s a quick mockup I made in Photoshop (since I don't know how to use FontForge) of an ſj ligature:

![disjointed](https://user-images.githubusercontent.com/10617484/37632288-eb400d7a-2bc3-11e8-8fd9-3b8e39431c88.png)

Much better.

**Comment by khaledhosny** [comment]
Looks good, if someone can make a pull request, I’ll merge.

**Comment by mgavioli** [comment]
See also https://github.com/khaledhosny/libertinus/issues/143
