### ISSUE TITLE
Strange output with overrightarrow & overletfarrow for libertinus math

### ISSUE THREAD

**Issue by Epaulard** [khaledhosny/libertinus#141]
Thanks for this nice font.

\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Libertinus Math}
\begin{document}
$\overrightarrow{AB} \overleftarrow{AB}$
\end{document}

gives strange results with Luatex.
Same code works fine with XITS Math instead of Libertinus Math.

**Comment by khaledhosny** [comment]
I can reproduce the issue with the version of the font in TeX Live but not with the local version, so whatever was the issue it seems to have been fixed in the meantime. I’l make a new release soon.

**Comment by Epaulard** [comment]
Thanks. I confirm I'm using the version of the font in TeXLive.
Here's the output.
![image](https://user-images.githubusercontent.com/30834296/37738278-c6bcca58-2d56-11e8-89e3-60b7b04bfd02.png)

**Comment by Epaulard** [comment]
I confirm issue is fixed with 6.5 
Here's the output
![image](https://user-images.githubusercontent.com/30834296/37802371-75b833ac-2e2a-11e8-9bf3-0c7e3078d0a0.png)
