### ISSUE TITLE
Reducing the serif in the number two

### ISSUE THREAD

**Issue by jco2** [khaledhosny/libertinus#142]
I find the serif in the number two too big:

![screenshot_20180323_225107](https://user-images.githubusercontent.com/29073309/37855284-e090a9a6-2eee-11e8-8885-6cf5005cf26a.png)

Here is an attempt at reducing this serif:
![screenshot_20180323_232956](https://user-images.githubusercontent.com/29073309/37855971-3db358ce-2ef2-11e8-9b05-a08f7e6013fb.png)

What do you think of this proposal ?

**Comment by khaledhosny** [comment]
I don’t think the current serif is too big or out of ordinary.

**Comment by jco2** [comment]
In retrospect I agree with you: the serif is not that big and gives character to the font.
