### ISSUE TITLE
\widehat too wide

### ISSUE THREAD

**Issue by JakobWerner** [khaledhosny/libertinus#144]
Compiling with LuaLaTeX the following code:

	\documentclass{article}
	
	\usepackage{fontspec}
	\usepackage{unicode-math}
	
	\setmathfont{Libertinus Math}
	
	\begin{document}
		\( \widehat{a} \)
	\end{document}

I get a very wide hat above the a. Unfortunately I don't know how to insert an image of the result here. I made sure to install the latest version of Libertinus. The problem does not occur with other math fonts so I suppose it's a bug here.

**Comment by khaledhosny** [comment]
Looks fine here:
![image](https://user-images.githubusercontent.com/93914/37902869-24405daa-30f6-11e8-92ff-c0b8713e298e.png)

(you can drag and drop images, or select them from the area at the bottom of comment box).

**Comment by JakobWerner** [comment]
Thank you. I added a line with another math font:

	\documentclass{article}
	
	\usepackage{fontspec}
	\usepackage{unicode-math}
	
	\begin{document}
		\setmathfont{Libertinus Math}
		\( \widehat{a} \)
		
		\setmathfont{STIX Two Math}
		\( \widehat{a} \)
	\end{document}

I get the following result:

![unbenannt](https://user-images.githubusercontent.com/37799533/37903191-47e24c90-30f7-11e8-9e3d-668c2cdceee7.PNG)

**Comment by khaledhosny** [comment]
This is how it looks here:
![image](https://user-images.githubusercontent.com/93914/37903821-a36ba6fe-30f9-11e8-8f5b-8685e9b20f2a.png)
Are you using the latest version of the font, what is your LuaTeX version?

**Comment by JakobWerner** [comment]
Yes, I downloaded the latest build of the font from github. LuaTeX version is 1.0.4 from TeX Live 2017. I just tried XeTeX and `\widehat` works fine with it.

**Comment by khaledhosny** [comment]
Check near the end of the LuaTeX log, it should show the font file paths it is using, it might still be using the old version supplied by TeX Live.

**Comment by JakobWerner** [comment]
It seems your guess was correct:

    <c:/texlive/2017/texmf-dist/fonts/opentype/public/lm/lmroman10-regular.otf>
    <c:/Windows/fonts/stix2math.otf>
    <c:/texlive/2017/texmf-dist/fonts/opentype/public/libertinus/libertinusmath-regular.otf>

When I explicitly specify the Libertinus Math version installed in my system fonts folder, the output is correct. Sorry for bothering you then. And thank you for resolving my issue.

**Comment by khaledhosny** [comment]
Glad that the issues is solved.
