### ISSUE TITLE
Monospace glyphs

### ISSUE THREAD

**Issue by godbyk** [khaledhosny/libertinus#15]
Here are a list of glyphs missing from the math font that can be copied from the existing Libertinus Mono font:
- [ ] Math monospace digits 0–9 (U+1D7F6 through U+1D7FF, `\mttzero` through `\mttnine`).
- [ ] Monospace uppercase Latin A–Z (U+1D670 through U+1D689, `\mttA` through `\mttZ`)
- [ ] Monospace lowercase Latin a–z (U+1D68A through U+1D6A3, `\mtta` through `\mttz`)

(These glyphs are low priority, but also low-hanging fruit.)

**Comment by khaledhosny** [comment]
Not using the Mono font for the corresponding math alphabets was intentional, I don’t like the design of the mono font and I’m looking for a better one.
