### ISSUE TITLE
Add support for petite caps

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#152]
Seen from #78, I found small caps letter looks a bit higher then x-height in Libertinus Serif, so I hope Libertinus Serif can implement pepite caps. 
Also see:
https://sourceforge.net/p/linuxlibertine/feature-requests/149/
https://sourceforge.net/p/linuxlibertine/bugs/295/

**Comment by waldyrious** [comment]
@KrasnayaPloshchad there's a typo in the title and the comment above: "pepite" should be "petite".

By the way, here are some relevant passages from the first link, for context:

> Sam (OP): "Small Caps are miniature capital variants which are just above x-height, whereas petite caps are meant to be just a bit smaller, exactly at x-height if memory serves."

> Philipp H. Poll: "Small caps are usually a bit larger than x-hight due to the geometry of the capital letters and the optical density. Why should we provide smaller Small caps though we know it would be the graphically inferior solution?"

> Sam (OP): "I only ask for this option because, depending upon the context, I find pmcp to be less jarring. It is likely not noticeable to anyone used to small capitals anyway; but, for me, because small caps tend to ascend above x-height, it doesn't look quite as natural as it could (certaily moreso than All caps, obviously). In certain contexts, I feel it could provide a better stylistic alternative."

**Comment by khaledhosny** [comment]
Too much work for little benefit. Anyone is free to contribute this if they are interested.
