### ISSUE TITLE
Add 𝚜𝚊𝚕𝚝 feature for Cyrillic Ef

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#156]
Seen from #145 I think Libertinus Serif font can make both these glyphs accessable, as my suggection, left is default form, right is available as `salt` feature.
![1](https://i.imgur.com/vz5OrWZ.jpg)

**Comment by nsemrau** [comment]
I guess this could be considered as a backwards compatability option for people who already set documents with the old version and want to keep that for the sake of consistency.

**Comment by khaledhosny** [comment]
Since no one knows what this variant is for and no one complained about it being gone, I see no point in adding features that no one will use. Closing until someone who needs this actually complains.
