### ISSUE TITLE
Add alternates for Cyrillic De, El, Nje

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#158]
Wikipedia [article](https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet) showing a special variant for De, Le, Nje. Maybe Libertinus can made similar implementation.
![1](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/%D0%A1%D1%80%D0%BF%D1%81%D0%BA%D0%B0_%D0%B2%D0%B0%D1%80%D0%B8%D1%98%D0%B0%D1%86%D0%B8%D1%98%D0%B0_%D0%9B%D0%89%D0%94.svg/220px-%D0%A1%D1%80%D0%BF%D1%81%D0%BA%D0%B0_%D0%B2%D0%B0%D1%80%D0%B8%D1%98%D0%B0%D1%86%D0%B8%D1%98%D0%B0_%D0%9B%D0%89%D0%94.svg.png)
EB Garamond also has this variant.

**Comment by khaledhosny** [comment]
We would be lucky to fix the existing Cyrillic bugs. Feel free to submit a pull request implementing this, though.
