### ISSUE TITLE
Libertinus Math and PDF: big root symbol broken

### ISSUE THREAD

**Issue by PeterHeidrich** [khaledhosny/libertinus#159]
Using Libertines Math in Microsoft Word 2016, applied to a simple equation containing a big root:
(i) the big root is shown correctly on the screen
(ii) but the PDF output is broken (independently from the printer, either Microsoft or Adobe or Ghost).
Word file and PDF file are attached.
[test.docx](https://github.com/khaledhosny/libertinus/files/1910045/test.docx)
[test.pdf](https://github.com/khaledhosny/libertinus/files/1910046/test.pdf)
Regards,
Peter.

**Comment by khaledhosny** [comment]
Isn’t this the same issue as #103?
