### ISSUE TITLE
Why forking?

### ISSUE THREAD

**Issue by rolfn** [khaledhosny/libertinus#16]
Dear Khaled,
thanks for working  on this font. My question: Why do you fork this project under a new name? I think the new name is a bit confusing. I see no reason not modify the Libertine/Bi­olinum fonts directly as a new maintainer. The original author would probably be happy with such solution.

Greetings from Berlin,
...Rolf

**Comment by davelab6** [comment]
The OFL's "Reserved Font Name" requires modified versions to use another name, and the upstream project has been dormant. Those are both very good reasons :)

**Comment by sieversMartin** [comment]
@davelab6 If it is dormant, why not wake it up? Rolf suggested, that Khaled takes over the maintenance of the libertine which would have been possible IMHO.

**Comment by alerque** [comment]
@rolfn If you think the original author would be happy for that outcome and to take the old fonts the direction this fork is going, then why don't you contact them and confirm? They are welcome to pull in changes at any time or turn over the original name/site/etc. But getting all that arranged takes work, including work the original author may or may not be up for.

If you want to see this happen the best place to report this is actually on the _upstream_ project. Forks happen in the Open Source world most often when authors move on to other things in life or somebody wants to take a bit of a different direction. If the upstream project was active and responsive to requests, this fork would probably never have happened.

@rolfn and @sieversMartin If you think you can wake it up, maybe that can be your contribution. But the waking up that needs to happen is on the other end of the stick, so if you have contacts and can make a case for this with them, then great.

**Comment by khaledhosny** [comment]
I think @davelab6 and @alerque summed it up.

**Comment by alerque** [comment]
If we've addressed the _why_ question I think this issue can be closed. If there is ever progress on this front (as in one of the former devs gets woken up and wants to merge efforts somehow) the best thing to do would probably to make a specific proposal for how that would work in a new issue.
