### ISSUE TITLE
Error when using Libertinus Serif with lualatex, siunitx, and unicode-math

### ISSUE THREAD

**Issue by lunik1** [khaledhosny/libertinus#166]
```tex
\documentclass[english]{article}

\usepackage{fontspec}
\usepackage{unicode-math}
\usepackage{siunitx}

\setmainfont{Libertinus Serif}

\begin{document}
\si{\per\femto\barn}
\end{document}
```
The above latex document will not build on two of my Arch Linux machines using the Libertinus Serif from the texlive-fontsextra package. The error given is: `error:  (nodes): attempt to double-free noad node 100314, ignored`

The following does work:
- Using a different font (Libertinus Mono, Libertinus Sans, Libertinus Math all work)
- Disabling unicode-math
- Removing the `\per`
- Removing or replacing `\femto` with a different prefix (`\Mega`, `\pico`, etc.)
- Replacing `\barn` with another unit

It's very... specific, and I'm not sure what is responsible for the bug. I'm reporting it here since Libertinus Serif is the only font I've found that is affected.

**Comment by jabirali** [comment]
I just tried compiling that code snippet on Linux Mint 18.3, using LuaLaTeX 1.0.4 (from the final and frozen version of TeX Live 2017), with the latest git-version of Libertinus. I reproduced exactly the same error:
`! error:  (nodes): attempt to double-free noad node 100314, ignored`
`!  ==> Fatal error occurred, no output PDF file produced!=== TeX engine is 'LuaTeX'`

**Comment by khaledhosny** [comment]
That sounds like a LuaTeX bug, even if the font is buggy the engine shouldn’t crash.

**Comment by khaledhosny** [comment]
I get the crash with other fonts as well; Amiri, STIX Two Text, but not with Noto Serif or DejaVu Serif. Definitely a LuaTeX issue.
