### ISSUE TITLE
there is no \square on the math font!

### ISSUE THREAD

**Issue by vagol942** [khaledhosny/libertinus#167]
Neither \blacksquare, I really need that symbol for my thesis, and I don't want to change the font, it took me 6 hours to settle with libertinus.

**Comment by jabirali** [comment]
Are you sure this is an issue with Libertinus Math, and not with e.g. a macro missing from the `unicode-math` package? If I write the unicode `$1■2□3$` directly, it renders fine om my computer:
![screenshot at 2018-04-25 13-13-40](https://user-images.githubusercontent.com/271284/39242495-7d760af4-488a-11e8-89bf-5e109a826d44.png)
(Those symbols are codepoints "25A0 'black square' and "25A1 'white square'.)

**Comment by khaledhosny** [comment]
I checked `unicode-math-table.tex` and it has neither `\square` nor `\blacksquare`, it has however:
```tex
\UnicodeMathSymbol{"025A0}{\mdlgblksquare            }{\mathord}{square, filled}%
\UnicodeMathSymbol{"025A1}{\mdlgwhtsquare            }{\mathord}{square, open}%
```
