### ISSUE TITLE
Weird arrows with mhchem

### ISSUE THREAD

**Issue by krishnakumarg1984** [khaledhosny/libertinus#168]
I am using the ```mhchem``` package with the ```Libertinus``` font family in my PhD thesis. 

When typesetting with LuaTeX, there are some weird issues with arrows depicting reactions. Here is the MWE to reproduce my issue.

    %! TEX program = lualatex
    \documentclass[varwidth=true, border=10pt, convert={size=640x}]{standalone}
    \usepackage[version=4]{mhchem}
    \usepackage{unicode-math}
    \setmainfont[Numbers={Proportional},Ligatures={TeX, Common%, Historic, Contextual, Rare, Discretionary
    }]{Libertinus Serif}
    \setmonofont[Scale=0.8]{Libertinus Mono}
    \setsansfont{Libertinus Sans}
    \setmathfont{Libertinus Math}
    \begin{document}
    \ce{A <=> B + C}
    \vspace{5mm}
    \ce{A <-->[long forward]B + C}
    \vspace{5mm}
    \ce{X <-->Y + Z}
    \end{document}

This code produces the following PDF output

[![image of weird arrows in chemical equations][1]][1]

In the first equation, notice the weird break in the forward reaction. In the second equation, it is clear that the arrows do not remain straight. The forward reaction arrow is clearly bent upwards, whilst the reverse reaction also seems to be made of two separate arrows with an overlap error.  The third equation also shows the same problem, but you will have to squint a little bit to see the issue.

I tried first with TL2017 and later on with Tl2018-pretest, but the same issue persists in both. What could be the source of the issues and how to fix them?  Does this look like a bug with the fonts? (or could it be in mhchem or LuaTeX itself?) 

  [1]: https://i.stack.imgur.com/5TSIu.png

**Comment by khaledhosny** [comment]
I can’t run your example with LuaTeX as all, I get multiple errors. It runs fine, however, with XeTeX and the output is just fine. Do you have the last version of the fonts?

**Comment by krishnakumarg1984** [comment]
That is abolsutely weird. I just ran it with 

 ```lualatex -interaction=nonstopmode -shell-escape demo.tex```

where ```demo.tex``` is the name of the main file.  [Here ](https://gist.github.com/krishnakumarg1984/107369a091a742bbbb36694d7e64221d) is the output log file from that run.

**Comment by khaledhosny** [comment]
I can run the document by using `article` class instead of `standalone` and I see the Issue but only with LuaTeX.

**Comment by krishnakumarg1984** [comment]
Thank you for your reply.  

I just tried running ```xelatex``` with the ```article``` class.  The original issue persists in the PDF output.

A temporary workaround is to use pgf-arrows rather than the font's arrows by using this line in the preamble.

```\usepackage[version=4]{mhchem}```

**Comment by khaledhosny** [comment]
Looks like you have and old version of the fonts, as this issue was fixed in the last releases. My LuaTeX was using the fonts shipped by my distro’s TeX Live package which is still old, by XeTeX was using system version which is new. Copying the new fonts to the current directory where LuaTeX is run fixes the issue.

**Comment by krishnakumarg1984** [comment]
Thank you for the fix and sorry for the noise. I checked in TL2018 -pretest and does not seem to be fixed?

Will the version with the fixes be pushed to CTAN in time for TL2018 release (in 4 days time I believe)?

**Comment by khaledhosny** [comment]
My bad, I didn’t actually make a release with this fix yet! Thanks for reminding me, releasing and uploading to CTAN now. Not sure it will make it to TeX Live before the release.

**Comment by krishnakumarg1984** [comment]
Thank you. No issues at all.  May I politely ask you to consider removing the ```invalid``` tag, since the issue looks like a reasonable one?
