### ISSUE TITLE
Math mode typesetting does not work with mhchem equations

### ISSUE THREAD

**Issue by krishnakumarg1984** [khaledhosny/libertinus#169]
I am using the Libertinus math font family with luatex for my PhD thesis. For chemical equations, I am using the ```mhchem``` package.

The problem is that inside ```align``` environments, I cannot obtain any characters in math-mode, i.e. italics (even if I explicitly coax it by surrounding  desired constructs with $ ... $). Here is a minimum example.

    %! TEX program = lualatex
    \documentclass[varwidth=true, border=10pt, convert={size=640x}]{standalone}
    \usepackage[version=4,arrows=pgf]{mhchem}
    \usepackage{unicode-math}
    \setmainfont[Numbers={Proportional},Ligatures={TeX, Common%, Historic, Contextual, Rare, Discretionary
    }]{Libertinus Serif}
    \setmonofont[Scale=0.8]{Libertinus Mono}
    \setsansfont{Libertinus Sans}
    \setmathfont{Libertinus Math}
    
    \begin{document}
    
    \begin{center}
    \ce{A_x <=> B + y C} \\
    \end{center}
    
    \begin{align}
        \ce{A_x &<=> B + y C} \\
        \ce{X + Y &-> Z}
    \end{align}
    
    \begin{align}
        \ce{A_$x$ &<=> B + $y$ C} \\
        \ce{X + Y &-> Z}
    \end{align}
    
    \end{document}

In the first equation, I obtain the correct behaviour, i.e. both ```x``` and ```y``` are correctly italicised.  But in the next two equations, I cannot get this desired behaviour. Especially in the third equation, even after surrounding ```x``` and ```y``` with $..$, it still typesets them upright as shown below

[![wrong typesetting][1]][1]

If I comment the lines that set up the ```Libertinus``` font family as shown below

    %! TEX program = lualatex
    \documentclass[varwidth=true, border=10pt, convert={size=640x}]{standalone}
    \usepackage[version=4,arrows=pgf]{mhchem}
    % \usepackage{unicode-math}
    % \setmainfont[Numbers={Proportional},Ligatures={TeX, Common%, Historic, Contextual, Rare, Discretionary
    }]{Libertinus Serif}
    % \setmonofont[Scale=0.8]{Libertinus Mono}
    % \setsansfont{Libertinus Sans}
    % \setmathfont{Libertinus Math}

and retain the rest of the source code, a luatex run gives me the correct output for all 3 cases, as shown below

[![correct typesetting without libertinus][2]][2]

whereupon ```x``` and ```y``` are typeset correctly in italic. Can I confirm that this is a bug with Libertinus ? Is there a way to borrow an alternative font just for these glyphs?

Note that for the arrows in the reaction, I am temporarily using ```pgf-arrows``` as a workaround, until  #168 gets fixed.

  [1]: https://i.stack.imgur.com/6213B.png
  [2]: https://i.stack.imgur.com/eEGv1.png

**Comment by khaledhosny** [comment]
I get italic but not math glyphs if I keep `unicode-math`, so seems a `unicode-math` issue and not font specific.

**Comment by krishnakumarg1984** [comment]
Sorry. I did not quite catch that. Can you please post a screenshot, or give me a bit more explanation to reproduce what you did? This will help me with better information to file a bug with the ```unicode-math``` developers.

**Comment by khaledhosny** [comment]
Just keep the `\usepackage{unicode-math}` line and keep the `\set*font` lines commented out.
