### ISSUE TITLE
Ligatures in the italic font seems to be mapped incorrectly

### ISSUE THREAD

**Issue by hmenke** [khaledhosny/libertinus#174]
### Problem

In this minimal working example the ffi ligature is missing.  Originally reported at https://tex.stackexchange.com/q/430249
```latex
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Libertinus Serif}

\begin{document}
    Affine finance

    \itshape Affine finance
\end{document}
```
![](https://i.stack.imgur.com/WqWTm.png)

### Expected behavior

The ligatures show up.

### What has been tried to remedy the problem

I checked the font `libertinusserif-italic.otf` as shipped with TeX Live 2018 in Font Forge and found that many of the ligatures are unmapped.

![](https://i.stack.imgur.com/mfNyS.png)

![](https://i.stack.imgur.com/VTkka.png)

**Comment by u-fischer** [comment]
It works with mode=base but not with mode=node. I could also reproduce the problem with a current context minimals after replacing the existing fonts (from 2017) with the newest version from a texlive  2018:

~~~~
\starttext

   \font\test={file:libertinusserif-regular.otf:mode=base;script=latn;language=DFLT;+liga;}
    \test ffi

    \font\test={file:libertinusserif-regular.otf:mode=node;script=latn;language=DFLT;+liga;}
    \test ffi


    \font\test={file:libertinusserif-italic.otf:mode=base;script=latn;language=DFLT;+liga;}
    \test ffi

    \font\test={file:libertinusserif-italic.otf:mode=node;script=latn;language=DFLT;+liga;}
    \test ffi

\stoptext
~~~~

![image](https://user-images.githubusercontent.com/4047173/39672232-67de3834-5126-11e8-87bb-4ca6f58969be.png)
