### ISSUE TITLE
Slanted versions of the fonts

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/libertinus#18]
Some TeX users are requesting slanted fonts in keeping with Computer Modern tradition of having both italic and slanted. Not sure of mechanical slanting can cut it, but lets track it here.

**Comment by Amphiboly** [comment]
Can you work from the existing ttf Libertine slanted fonts?

**Comment by khaledhosny** [comment]
This does not appear to be in the sources, so I guess it was automatically generated.

**Comment by khaledhosny** [comment]
Not going to do that.
