### ISSUE TITLE
Libertinus maths - brackets with fraction inside looks truncated in MS Word

### ISSUE THREAD

**Issue by ClaudioDiF** [khaledhosny/libertinus#19]
Hi Khaled, 
Following up my email, I report here the bug I noticed in MS Word (2010) - I am not sure if happens also with the LaTeX.

When I write a fraction within round brackets, the brackets appear truncated and smaller than the fraction. They are definetely different from the appearance in the file "libertinus-testmath.pdf"

I also noticed other aesthetic problems with the square brackets, the square root symbol, the integral symbol, the double integral symbol, slash with fractions, summation symbol, etc. Please find below the attached files with all the examples I am referring to.

[Libertinus math bugs.pdf](https://github.com/khaledhosny/libertinus/files/116364/Libertinus.math.bugs.pdf)

[Libertinus math bugs.docx](https://github.com/khaledhosny/libertinus/files/116365/Libertinus.math.bugs.docx)

All the best,
Claudio

**Comment by khaledhosny** [comment]
Looks like a Word bug. Word does not seem to support embedding fonts with PostScript outlines in PDF, so it rasterizes them into bitmaps, and seems there is something broken is this process. No idea if there is anything specific to the font that is triggering this, and I probably will never know. I suggest using one of the third party PDF printers that do not suffer from Word’s limitation.

**Comment by datbnh** [comment]
I understand that this is not the bug of the font, but just wonder if anybody has a solution? I'm suffering from this, too.
