### ISSUE TITLE
Minus sign not aligned with fraction bar

### ISSUE THREAD

**Issue by Matzeee** [khaledhosny/libertinus#25]
At first: Thank you very much for your great work!

I think the minus sign is not correctly aligned with the fraction bar.
It is already visible in the supplied `libertinus-testmath.pdf`, but I created an example to make it clearer.

This also causes a problem with `\xrightarrow` etc.
On some zoom steps, every single minus sign is visible.

![minus fraction bar](https://cloud.githubusercontent.com/assets/6171490/13174251/abf70f50-d702-11e5-977e-980dc5276c23.jpg)

In XITS Math, they are almost perfectly aligned.
(The fraction bar is a tiny little bit lower, but `\xrightarrow` is perfect)

**Comment by fred-wang** [comment]
I noticed that bug too while running my MathFonts script on Libertine Math. This is a problem with the AxisHeight value.

**Comment by khaledhosny** [comment]
I’ll try to fix this, but abusing minus for extensible arrows is just a XeTeX limitation (inherited from TeX), the font already supports proper extensible arrows.

**Comment by jmaibaum** [comment]
This not only affects the minus sign, but also plus and equality, and probably other operators, see for example:
![+ and = also not aligned](https://cloud.githubusercontent.com/assets/3957164/13702255/78af6e4e-e78d-11e5-9077-9fd9a8305115.png)

**Comment by Matzeee** [comment]
I really do not want to be impolite, but could you have a look at this again?

For me it is the only issue that stops me from using Libertinus and I did not find any combination of regular, sans, mono and mathfont that looks comparably well.

Or is it worth a try to report this as a TeX bug or enhancement?

**Comment by fred-wang** [comment]
@khaledhosny So isn't the issue that the AxisHeight value from the MATH table does not match the middle of the + and - signs?

**Comment by khaledhosny** [comment]
I’m wondering about this as well, and also wondering how it never occured to me before. Let me try and see.

**Comment by khaledhosny** [comment]
I remember now. There are two issues here, the first one is axis height not aligned with +-=, and the other is arrow glyphs not aligned with the minus sign. The first is simple to fix, the second needs some work.

**Comment by khaledhosny** [comment]
The minus should be aligned with the fraction bar now, but still not aligned with the arrows.

**Comment by khaledhosny** [comment]
![screenshot](https://user-images.githubusercontent.com/93914/37991674-17dfbf3c-320a-11e8-903d-b5e3ae0aed0f.png)

**Comment by khaledhosny** [comment]
All should be fixed now:
![screenshot](https://user-images.githubusercontent.com/93914/37993840-160002ac-3210-11e8-8679-dcb8cf6485b7.png)
