### ISSUE TITLE
Support alternate glyphs for Hanyu Pinyin

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#26]
The official Hanyu Pinyin specification has some different shapes from many Latin based scripts.
1. a looks similar to handwritten style
2. tone 2 looks like reversed acute

You can seen from following official sources: 
http://www.moe.gov.cn/s78/A19/yxs_left/moe_810/s230/195802/t19580201_186000.html 
http://www.china-language.gov.cn/126/2008_2_1/3_126_3278_0_1201864229916.html
http://www.moe.gov.cn/publicfiles/business/htmlfiles/moe/s230/201001/75607.html

Additionaly, seen from _Xiandai Hanyu Cidian_ (现代汉语词典, 現代漢語詞典) and _Xinhua Zidian_ (新华字典, 新華字典), these letters have different mark positing from Vietnamese: ế, ề

**Comment by moyogo** [comment]
1. This is a misinterpretation of some of the Hanyu Pinyin specification documents. They use a font with a single-storey a, but they don’t actually specify that as the only valid form. BTW one of the documents mentioned uses a double-storey a.
2. Same issue, it’s a font choice not a directive.
However, these can be personal preferences, in particular the single-storey a, and could be alternate glyphs.

For the stacked mark positioning, that’s a good point, other writing systems also prefer the proposed alternate positioning.

**Comment by KrasnayaPloshchad** [comment]
Another case can be found in SimSun/NSimSun font, which these special glyphs in Latin blocks:
![Pinyin styled glyph in SimSun](https://i.imgur.com/id7Msd2.png)
They can also found in FangSong, KaiTi, LiSu, SimHei, SimKai_GB2312 and YouYuan fonts.

As I know, these alternates for Pinyin used very common in dictionaries and textbooks published from PR China, so I suggest to implement. Additionaly, I think they can be intergrated as style set `ss01, ss02, ...`.

**Comment by khaledhosny** [comment]
https://github.com/khaledhosny/libertinus/issues/55#issuecomment-294378992
