### ISSUE TITLE
\scriptstyle\left(\right) produces wrong output in xelatex

### ISSUE THREAD

**Issue by PetrosTravioli** [khaledhosny/libertinus#31]
Dear maintainer:
consider the following code:
```
\documentclass{article}
\usepackage{unicode-math}
\setmathfont[Extension=.otf]{libertinusmath-regular}
\begin{document}
\(\scriptstyle \left(\right)\)
\end{document}
```
The output, when compiled with xelatex, are two crossed boxes. They should be really parentheses.
![q](https://cloud.githubusercontent.com/assets/18057861/14266276/58474666-fac7-11e5-85f0-3c4a7cbd1460.jpg)
The same bug occurs with \mleft, \mright from the package mleftright.
No bug occurs with lualatex. No bug occurs when other fonts are used, e.g. TeX Gyre Pagella.
Any chance for a bugfix?

**Comment by khaledhosny** [comment]
That sounds like a bug in XeTeX, if I check the log I see the following message:
````
Missing character: There is no අ in font Libertinus Math/OT:script=math;languag
Missing character: There is no ආ in font Libertinus Math/OT:script=math;languag
````
It seems like XeTeX is trying to access some Sinhalese character which does not seem right.

**Comment by PetrosTravioli** [comment]
Ok; see [https://sourceforge.net/p/xetex/bugs/129](https://sourceforge.net/p/xetex/bugs/129).
