### ISSUE TITLE
Adding GPL+Font exception license

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#32]
The original Linux Libertine and Linux Biolinum fonts were licensed under both OFL and GPL+Font exception, but Libertinus is licensed under OFL only, need GPL+FE to follow it.

**Comment by alerque** [comment]
What do you mean by:

> need GPL+FE to follow it.

Usually when things are dual licensed it means that recipients can choose to use the product under the conditions of the license of their choice. If you like A better and it suits your use case, follow the conditions of license A, but if B is a better match for you follow the conditions of B.

As such a fork project can choose to take the original work under the license of their choice and add their contributions under only that license. There is no requirement that the union of terms from  _both_ licenses are followed, only that one set of terms is followed.

That seems to be what this project chose to do and personally I think it's a good move. The OFL is much better suited to the needs of a font in the first place and I don't see what GPL+FE has to add.

What use case do you have that you cannot use this font under OFL but "need" it licensed under GPL+FE instead?

**Comment by khaledhosny** [comment]
What @alerque said. I intentionally dropped GPL as I don’t think it is a good font license, and because I want to be able to mix with other OFL licensed fonts.

**Comment by davelab6** [comment]
I agree dropping GPL+FE is good. KP, do you understand why the OFL was
written? :)

**Comment by KrasnayaPloshchad** [comment]
I understand, you decided to give it up, thanks.

**Comment by davelab6** [comment]
My point is wider than just Libertine; I think the GPL+FE is a bad idea, as did the authors of the OFL license, which is why it was made. I'm curious why you think GPL+FE would be a good idea :)
