### ISSUE TITLE
Complete several blocks

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#33]
The following blocks should be completed:
- Combining Diacritical Marks
- Currency Symbols
- Cyrillic (several non-Slavonic letters)
- Dingbats (circled digits)
- Enclosed Alphanumerits
- Greek and Coptic, except some “Coptic” letters of this block
- Hebrew
- Latin Extended-C and -D
- Letterlike Symbols
- Mathematical Operators
- Miscellaneous Mathematical
- Miscellaneous Technecal
- Number Forms
- Phonetic Extensions
- Phonetic Extensions Supplement

**Comment by Crissov** [comment]
I believe this should be tracked in several separate issues.

**Comment by khaledhosny** [comment]
That is so much work that I can dedicate to this project.
