### ISSUE TITLE
Bad math spacing behind italic and bold+italic f

### ISSUE THREAD

**Issue by timtro** [khaledhosny/libertinus#36]
Thank you, so much, in advance.

The following MWE illustrates the issue. The `\lVert` nearly runs into the tail of the italic _f_ in math mode. I believe the same goes for the bold version. In the MWE, I compare with CMR.

```
%!TEX program = lualatex
%
\documentclass{article}
\usepackage{unicode-math}

\begin{document}
\[\lVert f \rVert\]
\setmathfont{Libertinus Math}
\[\lVert f \rVert\]
\end{document}
```

This, for me, produces the following
![screenshot from 2016-05-05 11-48-36](https://cloud.githubusercontent.com/assets/329007/15048658/6ba663b4-12b8-11e6-9d84-9abb60d57f4d.png)

Here are my versions: (let me know if I missed something important)

Libertinus, Latest git
LuaTeX, Version beta-0.80.0 (TeX Live 2015/Debian) (rev 5238)
luaotfload.sty    2015/12/09 v2.6 OpenType layout system
lualatex-math.sty    2015/09/22 v1.5 Patches for mathematics typesetting with Lu
unicode-math.sty    2015/09/24 v0.8c Unicode maths in XeLaTeX and LuaLaTeX
fontspec.sty    2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTeX

Thanks again. I'm willing to help, but I have no experience with font editing to speak of. Let me know if there is anything I can do.

**Comment by timtro** [comment]
I realized that I wasn't sure if the spacing problem may have had something to do with the Vert, so I also tried loading \vert from other math fonts, and it didn't help.

**Comment by khaledhosny** [comment]
I guess this is because the italic f has a negative left side bearing. Should be easy to fix.

**Comment by timtro** [comment]
I've installed font forge. I admit to not knowing where to start, but I'm willing to look into it if I can help.

**Comment by khaledhosny** [comment]
I’m on it, there is also the italic j and the sans serif ones.

**Comment by khaledhosny** [comment]
Here is how it looks now:
![a-crop-1](https://cloud.githubusercontent.com/assets/93914/15054912/8412beac-1312-11e6-9be7-1d9af4a5802f.png)

Fir references, all was needed is to move the glyph so that the side bearing is positive (I made it 20 units to be the same as the space after 𝑓’s italic correction) and adjust the top accent position and the advance width of the glyphs.

**Comment by timtro** [comment]
Brilliant mate. Thanks so much for your work. I've wanted to use Libertine in my documents for years. I have to say, Libertinus looks better than I ever hoped. You made some really brilliant choices too.

**Comment by khaledhosny** [comment]
Thank you :)
