### ISSUE TITLE
Cramped spacing around \sum

### ISSUE THREAD

**Issue by timtro** [khaledhosny/libertinus#37]
The gap beneath the big Sigma in \sum is a bit cramped if the bottom limit has a symbol with cap height. If the top limit has a descender, it also seems to be cramped from above. MWE and illustration follows.
```
%!TEX program = lualatex
%
\documentclass{article}
\usepackage{unicode-math}

\begin{document}
\[
  \sum_{k=1}^{N-1}\;\sum_{A=1}^{g-1}\;\sum_{H=1}^{p-1}
\]
\setmathfont{Libertinus Math}
\[
  \sum_{k=1}^{N-1}\;\sum_{A=1}^{g-1}\;\sum_{H=1}^{p-1}
\]
\end{document}
```

![screenshot from 2016-05-05 14-08-09](https://cloud.githubusercontent.com/assets/329007/15052292/de83fdee-12ca-11e6-9c9a-2a84c46a588e.png)

Here are my versions: (let me know if I missed something important)

Libertinus, Latest git
LuaTeX, Version beta-0.80.0 (TeX Live 2015/Debian) (rev 5238)
luaotfload.sty    2015/12/09 v2.6 OpenType layout system
lualatex-math.sty    2015/09/22 v1.5 Patches for mathematics typesetting with Lu
unicode-math.sty    2015/09/24 v0.8c Unicode maths in XeLaTeX and LuaLaTeX
fontspec.sty    2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTeX

Thanks again. I'm willing to help, but I have no experience with font editing to speak of. Let me know if there is anything I can do.

**Comment by khaledhosny** [comment]
I increased the parameters controlling the minimum gap between the limits and the big operator, this is how it looks now:
![b-crop-1](https://cloud.githubusercontent.com/assets/93914/15055347/b2a73b56-1314-11e6-8603-6ac4edb4f1b9.png)

**Comment by timtro** [comment]
Absolutely brilliant. Thanks again.
