### ISSUE TITLE
Libertinus uses alternative glyphs for any numerals whose size are less than the base size

### ISSUE THREAD

**Issue by taikis** [khaledhosny/libertinus#40]
I have also posted about this issue on [tex.SE](http://tex.stackexchange.com/q/314535/29127).

For some reason, in the math mode, alternative glyphs are used for any numerals whose size is less than `\normalsize`, explicitly (that is, through `\small`, `\scriptsize`, `\footnotesize`, and `\tiny)` or implicitly (for example, through `^` and `_`), leading to unpleasant kerning for consecutive numerals etc etc. Is this an intended behaviour?

Currently I wrap all sub/superscripts in `\mathrm` as a workaround.

```
\documentclass{article}
\usepackage{unicode-math}
\setmainfont{Libertinus Serif}
\setmathfont{Libertinus Math}

\begin{document}

$1234567890^{1234567890}$

$1234567890^\mathrm{1234567890}$

\end{document}
```

[![1234567890^1234567890](http://i.stack.imgur.com/Uto2O.png)](http://i.stack.imgur.com/Uto2O.png)

**Comment by khaledhosny** [comment]
They are supposed to be used only for `\scriptsize` and `\scriptscriptsize`, if they are used anywhere else then it is an issue with LaTeX or the respective packages.

But I welcome any comment on the number themselves, they are based on Linux Libertine alternate glyphs for `sup` and `sub` OpenType features as I thought they are a good fit for the smaller sizes being designed for such usage, but may be they need more work to get them into shape.

**Comment by taikis** [comment]
Ah OK. It's fine since it's an intentional design choice; I shall close this issue then. But personally I feel that uniform glyphs for all sizes provide better look, especially in a maths/physics document.

**Comment by khaledhosny** [comment]
I might as will just kill them and use the regular digits, they look too intrusive to my liking actually (or may be just keep them for `\scriptscriptsize` where they might be less intrusive).

**Comment by taikis** [comment]
I vote for the regular glyphs for all sizes. This would eliminate LaTeX issues in which the alternative glyphs are picked up for sizes other than `\scriptscriptsize` (or whatever is specified).

**Comment by khaledhosny** [comment]
I think the problem might be is that Libertinus sets a bigger script sizes than traditional TeX (8pt and 6pt, respectively, compared to 7pt and 5pt). Here is a comparison between different combinations. I think if we set smaller script sizes they will look better, with no optical alternates at all they look much lighter:
![a-crop-1](https://cloud.githubusercontent.com/assets/93914/16017671/9a94926c-31a9-11e6-8f69-0a404665dd48.png)

**Comment by taikis** [comment]
Personally I find Libertinus's alternative glyphs to be a bit too bold and the kerning a bit off, making them a kind of visual disruption. Compared to Latin Modern, which has a perfect visual flow:

<img width="401" alt="screen shot 2016-06-14 at 06 44 11" src="https://cloud.githubusercontent.com/assets/15276544/16032307/64531ef0-31fc-11e6-8ccd-baf1fcd66004.png">

I think it might be best to stick with no alternatives for now until the weight and kerning are adjusted.

**Comment by jmaibaum** [comment]
The workaround is great for getting better looking numerals in all sizes (I find the alternate `7` to be especially off compared to rest), but it brings up other issues.

I just came accross this issue with the `\prime` symbol, which gets way too small with the `SizeFeatures` workaround:

![prime](https://cloud.githubusercontent.com/assets/3957164/17133179/636787f2-5325-11e6-9164-2d03baeffe39.png)

**Comment by taikis** [comment]
I run into this problem as well, so I use another font, eg Cambria Math, for primes.

`\setmathfont[range={"2032-"2034,"2057}]{Cambria Math}`

**Comment by khaledhosny** [comment]
OK, I disabled them for now until I have time to improve them. Please test and let me know if there are any issues.
