### ISSUE TITLE
Small caps? 

### ISSUE THREAD

**Issue by jrmiller82** [khaledhosny/libertinus#43]
Does this include serif small caps and sans serif small caps like the libertine package in latex? I can't seem to find them but I could just be dense. Thanks!

If they're not included, then that's a feature request.

**Comment by khaledhosny** [comment]
I have no idea about the LaTeX package, but the fonts here include small caps (as an OpenType feature, not a separate font).

**Comment by jrmiller82** [comment]
Is there a way to separate them out? Word and LibreOffice don't seem to use them correctly. They still make fake small caps.

**Comment by khaledhosny** [comment]
You can use [pyftfeatfreeze](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze) to create fonts where small caps (or any other feature) is on by default.

**Comment by KrasnayaPloshchad** [comment]
> Is there a way to separate them out? Word and LibreOffice don't seem to use them correctly. They still make fake small caps.

LibreOffice 5.3 and later can make true small caps via a syntex as `Libertinus Serif:smcp=1`.

**Comment by jrmiller82** [comment]
Agreed. I'd love to have a separate small cap font I can use in Libreoffice. They don't work in their current state.

**Comment by KrasnayaPloshchad** [comment]
I know this feature because Ask LibreOffice website have this [discussion](https://ask.libreoffice.org/en/question/82052/opentype-features-now-enabled-documentation/), and I have already tested this version.

**Comment by jrmiller82** [comment]
The small caps need to be separated out so you can just pick XYZ small caps in the font drop down instead of using the "small caps" attribute in the font dialog. Those always make fake small caps in both Word and Libreoffice.

**Comment by khaledhosny** [comment]
You can create them yourself if you need them see https://github.com/khaledhosny/libertinus/issues/43#issuecomment-247726083.

**Comment by jrmiller82** [comment]
If I knew how, I would.

**Comment by jrmiller82** [comment]
I was able to get them to work in LO 5.2 but not using this package, I had to download the Linux Libertine "G" fonts. But still, these won't work in Word either. 

Nonetheless, I don't understand your resistance to packaging the small caps fonts like every other small-cap font out there, where it's a separate font to pick in the main font picker. Then you can bake in correct kerning, letterspacing, etc.. for the font.

**Comment by alerque** [comment]
@jrmiller82 All those features already _are_ baked in. The font uses the proper underlying technology to accomplish this. What you are suggesting is a hack to work around legacy systems that don't actually support fonts properly. It seems simple enough for one use case, but then you need one font build for each permutation of features. Small-caps isn't the only feature in this font and if you multiply them all out you get hundreds of faces that would need to be built, maintained, installed and generally maintained separately. This when the font build already has all that stuff built in.

The suggested solution when you want to access a particular set of  features in a program that doesn't understand the basics of the font format (that's been on the market for  15 years now) is to create copies of the base font with the features you want turned on by  default. In fact the [pyftfeatfreeze](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze) readme has generating smal-caps only font variants as an example.

And just for the record, the "G"  (Graphite) font technology was a stop gap for supporting some languages that is largely obsolete by the  necessary capabilities having been brought to the main OpenType standard.

**Comment by KrasnayaPloshchad** [comment]
@jrmiller82 LO 5.3 is already released that you can get the way to access true small caps as I pointed out.

**Comment by j4nw** [comment]
For anyone arriving here from googling "libertinus small caps" in need of a baked version of the font, let me save you a few hours in this rabbit hole.

[pyftfeatfreeze](https://github.com/twardoch/fonttools-opentype-feature-freezer) (version 1.32.2 as of writing this comment) as mentioned in https://github.com/alerque/libertinus/issues/43#issuecomment-247726083 will only work for **Libertinus 6.11** or earlier. There will be some minor regressions in the font but if you simply want a baked small caps version of Libertinus for basic use and just get on with your project/life, it's most likely gonna be Good Enough.

Discussion explaining the likely cause at https://github.com/alerque/libertinus/issues/434#issuecomment-765610599

pyftfeatfreeze issue reported at https://github.com/twardoch/fonttools-opentype-feature-freezer/issues/29
