### ISSUE TITLE
Old style 6 semibold italic

### ISSUE THREAD

**Issue by maieul** [khaledhosny/libertinus#51]
A bug inherited from Linux Libertine

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Numbers=OldStyle]{Libertinus Serif}
\begin{document}
\textbf{\emph{6}}
\end{document}
```

The 6 look like a zero. I have corrected it on my fork of Linux Libertine, but it would be fun to correct it also in Libertinus.

**Comment by khaledhosny** [comment]
6, 7, 8 and 9 all were wrongly mapped, should be fixed now. Thanks for the report.

Curious to know more about your fork.

**Comment by maieul** [comment]
my fork only solved this issue, of wrongly mapped number…
