### ISSUE TITLE
Add more alphanumerics symbols

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#54]
These symbols encoded in:
* U+3248–324F, U+3252–325F, U+32B2–32BF (Enclosed CJK Letters and Months)
* U+1F100–1F169, U+1F170–1F189 (Enclosed Alphanumeric Supplement)

**Comment by khaledhosny** [comment]
See https://github.com/khaledhosny/libertinus/issues/55#issuecomment-294378992.
