### ISSUE TITLE
Support Latin sigla

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#55]
They are the abbreviations used in medieval Latin, some of them can be implemented by adding letters, some of them can be implemented by means of typography. I think Libertinus Serif is suitable to get support for them.

**Comment by alerque** [comment]
I've used Libertinus Serif for a smattering of Latin but am not familiar with sigla. Can you give some examples and point to documentation of what would need to be included? An example of a proper implementation in another font would likely help too.

**Comment by KrasnayaPloshchad** [comment]
OK, Wikipedia article [Scribal abbreviation](https://en.wikipedia.org/wiki/Scribal_abbreviation) has several samples from old books, also including some code charts from the Unicode Standard that indicate which of them used in medieval.

**Comment by khaledhosny** [comment]
There are no shortage of Unicode symbols one can add to the fonts, but I don’t see myself working on something like this. The fonts are big already and so many existing glyphs are messed up and need fixing. Patches are welcome of course if someone wants to add any new characters.
