### ISSUE TITLE
Transport to libertine is missing roman italic font

### ISSUE THREAD

**Issue by RobtAll** [khaledhosny/libertinus#57]
I see that recently, the TeX libertine font package now uses Libertinus fonts, instead of Linux Libertine and Linux Biolinum. All good.

However, the libertine roman italic font LinLibertine_RI.otf is still Linux Libertine O, Italic. But it should be Libertinus Serif, Italic.

This confuses users who select font by family name, rather than file name, in fontspec.

Also, the Libertinus Math font was not transported to libertine. Perhaps that is intentional.

**Comment by khaledhosny** [comment]
The TeX packages are developed independent of this repository. I suggest you contact the authors of these packages.

**Comment by RobtAll** [comment]
Ah! I supposed that the fonts were "pushed" from here instead of "pulled" from there. I will contact the other package devs. Anyway: Congratulations. I have been recommending Libertinus.

**Comment by alerque** [comment]
This is great news! I've got some TeX based build servers I need to go update.

**Comment by RobtAll** [comment]
Hi,

But be careful! I communicated this via e-mail to the maintainer of the
libertine package, and he denied it. He did not know about Libertinus
appearing in the libertine package.

The situation: In libertine, the Open Type fonts still have their old file
names (LinLibertine, LinBiolinum, etc). But if you open the fonts in a font
viewer, they say they are Libertinus.

I am using TeXlive 2016 on Ubuntu. That's what the distro send me now. And,
if I directly download from CTAN, that's what I get.

- Robert Allgeyer

**Comment by RobtAll** [comment]
Just now, Bob Tennent (libertine package) got back to me via e-mail. It turns out that the substitution of Libertinus for Libertine/Biolinum was accidental. The gist of it: An experiment was uploaded as live.

So, a corrected libertine package was just uploaded by him to CTAN, and will be available soon. It restores Libertine/Biolinum to the libertine package. No more Libertinus there.

_Sic transit gloria mundi._

Actually, I wasn't aware that the Libertine/Biolinum Open Type fonts were still under development. Whatever.

**Comment by khaledhosny** [comment]
Linux Libertine project itself is inactive, but I think the LaTeX package is actively maintained.
