### ISSUE TITLE
Graphite version for LibreOffice

### ISSUE THREAD

**Issue by Raemi** [khaledhosny/libertinus#6]
**EDIT:** after some googling, it seems that I confused things and the "Linux Biolinum G" is actually a graphite font that I got from here: http://www.numbertext.org/linux/ . So the issue is actually a feature request for graphite versions of the font, since LibreOffice only supports these.

Hi

I'm not sure what's causing this problem, but when I try to use extended opentype features in LibreOffice with the OTF files provided in this repository, it does not work.

As an example, see this screenshot:
![screenshot from 2015-10-16 09 30 00](https://cloud.githubusercontent.com/assets/100977/10536080/8e9632a6-73e8-11e5-9ba0-2cfe0b023aff.png)
The first line has the font "Linux Biolinum G:onum=1", the second line uses "Libertine Sans:onum=1". As you can see, for Linux Biolinum, oldstyle figures and thousand separation is working. For Libertine Sans, I get neither of these effects.

Is there anything I'm doing wrong, is LibreOffice broken, or are the OTF files broken in some way?

**Comment by khaledhosny** [comment]
Linux Biolinum G is a Graphite font (that what the G is for). not an OpenType one, and LibreOffice [does not support user selectable OpenType features](https://bugs.documentfoundation.org/show_bug.cgi?id=58941) (the support for Graphite feature is a hack and not even interoperable with other ODF implementations).

**Comment by khaledhosny** [comment]
I have no plans to make a Graphite version of the fonts, but I’ll keep this open just in case.

**Comment by khaledhosny** [comment]
I don’t think I’m going to do this.

**Comment by KrasnayaPloshchad** [comment]
@khaledhosny Don’t worry, if you want to do you can go to graphite.sil.org to see the documentations; also, you can see [UTN No.41](http://www.unicode.org/notes/tn41/), on this note you will see the usage and advantages of Graphite at section 4.

**Comment by RGB-es** [comment]
I just tested LibO 5.3 alpha and it supports (at least on Linux) the use of OpenType tables through extended font names, so I don't think that a graphite version is even needed. See here:
https://ask.libreoffice.org/en/question/82052/opentype-features-now-enabled-documentation/
Since then I tested small caps, old numerals, fractions, swashes... and everything works!

**Comment by KrasnayaPloshchad** [comment]
@RGB-es Oh yeah, I can also see the effect on LibO 5.3 beta1 on Windows.
