### ISSUE TITLE
Bad kerning in math for subscript  followed by `(`.

### ISSUE THREAD

**Issue by adityam** [khaledhosny/libertinus#64]
In `$V_T(x)$`, the parenthesis is almost touching the `T`.

<img width="170" alt="screen shot 2017-04-19 at 8 23 01 am" src="https://cloud.githubusercontent.com/assets/28448/25188416/d181d21a-24da-11e7-87cc-9a2064586a97.png">

This is also true for some of the other letters: `I`, `K`, `U`, `V`, `W`. 

The kerning between `V` and the subscript is also too large for almost all subscripts.

**Comment by khaledhosny** [comment]
Are you using LuaTeX, seems fine with XeTeX:
![image](https://cloud.githubusercontent.com/assets/93914/25188905/416c8048-2530-11e7-8a34-58e39c2a44d4.png)

**Comment by adityam** [comment]
Yes, this was with ConTeXt MkIV. So should I report this to the context mailing list?

Aditya

**Comment by khaledhosny** [comment]
Probably. I don’t know what is going on for sure, but I suspect something related to italic correction.

**Comment by alerque** [comment]
This might be similar to #50.

**Comment by khaledhosny** [comment]
The difference is that `MATH` table supports setting italic correction for glyphs and math layout engines are expected to apply them under certain conditions, which is not the case for regular OpenType text layout.
