### ISSUE TITLE
Unable to typeset matrix with TeX Live 2017

### ISSUE THREAD

**Issue by amyspark** [khaledhosny/libertinus#73]
Font version: tried with 6.0, .1, .2, and .3
TeX Live version: 2017 pretest, tried with xelatex and lualatex

When using `mathtools` and `unicode-math`, I cannot use Libertinus Math to typeset the closing brace of a matrix with 4 or more rows:

![test](https://cloud.githubusercontent.com/assets/13498015/26163287/99200032-3aff-11e7-8a90-13f12a7392af.png)

`test.tex`:

```tex
\documentclass{article}
\pagenumbering{gobble}

\usepackage{mathtools}
\usepackage{unicode-math}

\begin{document}

Libertinus Math:
\setmathfont{Libertinus Math}
\begin{equation}
  x = \begin{bmatrix}
    m \\
    \end{bmatrix} = 
    \begin{bmatrix}
      m_{1} \\
      m_{1} \\
    \end{bmatrix} = 
    \begin{bmatrix}
      m_{1} \\
      m_{1} \\
      m_{1} \\
    \end{bmatrix} = 
    \begin{bmatrix}
      m_{1} \\
      m_{1} \\
      m_{1} \\
      m_{1} \\
    \end{bmatrix}
\end{equation}

Asana Math:
\setmathfont{Asana Math}
\begin{equation}
  x = \begin{bmatrix}
    m \\
  \end{bmatrix} = 
  \begin{bmatrix}
    m_{1} \\
    m_{1} \\
  \end{bmatrix} = 
  \begin{bmatrix}
    m_{1} \\
    m_{1} \\
    m_{1} \\
  \end{bmatrix} = 
  \begin{bmatrix}
    m_{1} \\
    m_{1} \\
    m_{1} \\
    m_{1} \\
  \end{bmatrix}
\end{equation}
\end{document}

```

**Comment by khaledhosny** [comment]
Oops, should be fixed now. Any idea when is the final TeX Live 2017 release? I need to release a new version of the font to be included in the final release.

**Comment by sieversMartin** [comment]
AFAIK final updates from CTAN were integrated yesterday. Maybe you contact the TeX Live team directly and upload a new version to CTAN asap.

**Comment by khaledhosny** [comment]
I made a new release and uploaded it to CTAN, if it made it to final TL2017 that would be nice, otherwise people will get the update some time after the release.
