### ISSUE TITLE
Superscript n (U+207F) looks slanted in Libertinus Serif Italic

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#75]
When you run [BabelPad](http://www.babelstone.co.uk/Software/BabelPad.html) on Windows, check “List All Styles of Fonts” item in Font menu, and click Select Font button (black F) on the toolbar, then you will see [ⁿ](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts) looks sightly slanted if you select Libertinus Serif Italic. To keep design consistency, this glyph should be replaced by italic form.

**Comment by khaledhosny** [comment]
The glyph looks fine here, please attach a screenshot.
