### ISSUE TITLE
Support ø͘ (o + stroke + dot above right)

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#77]
This is a variant of [O͘](https://en.wikipedia.org/wiki/O%CD%98) used for Minnan POJ.

**Comment by moyogo** [comment]
I don’t believe ø͘ is used in the reference mentioned in the [O͘](https://en.wikipedia.org/wiki/O%CD%98) Wikipedia article. See the copy of  Douglas (1873), *Chinese English Dictionary of the Vernacular or Spoken of Amoy* on Archive.org, for example on [page xi](https://archive.org/stream/chineseenglishdict00doug#page/n16/mode/1up):
![screen shot 2017-05-22 at 11 08 15](https://cloud.githubusercontent.com/assets/1923747/26303674/4fff8686-3ee0-11e7-9bf0-d3ad444c7cf2.png)

It looks like a yet-to-be-encoded character. A similar character was proposed as LATIN SMALL LETTER O WITH CURL in http://std.dkuug.dk/jtc1/sc2/wg2/docs/n4079.pdf.

**Comment by KrasnayaPloshchad** [comment]
Oh, it looks like ɵ + dot above right.

**Comment by KrasnayaPloshchad** [comment]
Oh, I see, maybe we can add stylistic alternates for the code point of o-curl if it was received in Unicode.
