### ISSUE TITLE
Add full height variants to digits 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#79]
These variants are very suitable when Libertinus fonts used along with CJK fonts. They can be available with ASCII digits (U+0030-0039), also with certain Enclosed Alphanumerics.

**Comment by khaledhosny** [comment]
What are “full height” digits?

**Comment by KrasnayaPloshchad** [comment]
The full height digits means digits with cap height, these variants are suitable for some world processors includes individual Wentern and CJK font settings.

**Comment by khaledhosny** [comment]
Libertinus is not a CJK font.
