### ISSUE TITLE
Support for calligraphic characters in Libertine Math

### ISSUE THREAD

**Issue by capnrefsmmat** [khaledhosny/libertinus#8]
Calligraphic characters (the `\mathcal` range) don't appear to be supported in Libertine Math:

```latex
\documentclass[11pt]{article}
\usepackage{fontspec}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{amssymb}

\usepackage{unicode-math}

\setmainfont[Numbers=OldStyle,Ligatures=TeX]{Libertine Serif}
\newfontfamily{\Lpnum}[Numbers=Lining,Ligatures=TeX]{Libertine Serif}
\setsansfont[Ligatures=TeX]{Libertine Sans}

\setmathfont{Libertine Math}

\begin{document}
${\cal A B C D E F G H I J K L M N O P Q R S T U V W X Y Z}$ ${\cal H}_i$
\end{document}
```

produces, with both LuaTeX and XeTeX,

![screen shot 2016-01-19 at 9 52 04 am](https://cloud.githubusercontent.com/assets/711629/12421914/55e71dea-be92-11e5-97c2-37e08a2872bc.png)

XITS Math has a full range I can use with `\setmathfont[range={\mathcal,\mathbfcal}]{xits-math.otf}`, but it'd be nice if Libertine Math had its own set (perhaps borrowed from XITS or elsewhere).

Thanks for the otherwise lovely fonts.

**Comment by capnrefsmmat** [comment]
(Moving discussion here from #39.)

I've dug around for OpenType fonts with calligraphic alphabets under the Open Font License or similar; the only three I've found are XITS/STIX, Asana Math, and the brand-spanking-new [TeX Gyre DejaVu Math](http://ctan.org/tex-archive/fonts/tex-gyre-math), based on the DejaVu sans-serif font. (Not quite OFL, but the license seems very liberal.)

I put together some vaguely mathematical gibberish to test a few of the characters in actual use, plus the whole range of the alphabet, using Libertinus Math as the base.

Screenshots of each:
![screen shot 2016-05-21 at 2 25 18 pm](https://cloud.githubusercontent.com/assets/711629/15450091/e47a4f7c-1f5f-11e6-9f8a-22d83a187985.png)
![screen shot 2016-05-21 at 2 26 05 pm](https://cloud.githubusercontent.com/assets/711629/15450094/fcca8ef2-1f5f-11e6-8e82-cae30e07ed07.png)
![screen shot 2016-05-21 at 2 26 37 pm](https://cloud.githubusercontent.com/assets/711629/15450095/0fcfcae4-1f60-11e6-8095-caee6ab1ddf5.png)

The DejaVu characters don't seem to fit at all, but XITS seems like a fairly good match, and I may use its calligraphic characters until they can be added to Libertinus.

[Source: mathcal.tex.txt](https://github.com/khaledhosny/libertinus/files/275988/mathcal.tex.txt)

I hope this proves helpful.

**Comment by khaledhosny** [comment]
I’m fine with XITS if others agree it is a good match (it seems fine from these screenshots).

**Comment by godbyk** [comment]
Of those presented, XITS has my vote.

**Comment by khaledhosny** [comment]
Please test and report any issues with the script alphabet.

**Comment by capnrefsmmat** [comment]
Just swapped in the updated font to my thesis proposal. Looks very good. Thanks for the very quick update!

My only comment is that I am not sure about the placement of subscripts:

<img width="113" alt="screen shot 2016-05-23 at 12 13 19 am" src="https://cloud.githubusercontent.com/assets/711629/15460133/2eec0d9a-207b-11e6-8548-fd073ea2788e.png">

I'm not sure whether the subscript *t* should be pulled in closer; maybe it needs italic correction?

**Comment by khaledhosny** [comment]
Yes, the spacing of scripts alphabet in STIX leaves a a lot to be desired. I thought I fixed it to some degree in XITS, but I’ll look again.

**Comment by adityam** [comment]
Is it also possible to include the stylistic set for calligraphic. With `xits`, I can use the following:

```
\setupbodyfont[xits]
\starttext
$\cal ABCDE$
\setupmathematics[stylealternative={calligraphic}]
$\cal ABCDE$
\stoptext
```

but the same code does not work with Libertinus. Not sure if this is due to the missing stylistic set or the missing `.lfg` file

**Comment by khaledhosny** [comment]
Libertinus does not have alternate calligraphic alphabet, and since Unicode seem to have promised to encode one in the future, I’m going to wait for that.

**Comment by madsmh** [comment]
Any news on the calligraphic alphabet?
