### ISSUE TITLE
Some extensible accents are broken

### ISSUE THREAD

**Issue by MarcRdC** [khaledhosny/libertinus#80]
`\widehat` and `\widetilde` seem broken in latest 6.4 version: the first one is too wide whereas the latter doesn’t extend. Read also [this reference post](https://tex.stackexchange.com/questions/370282/scaling-of-delimiters-and-widetilde-does-not-work-with-libertinus) on TeX Stack Exchange website.

**Comment by khaledhosny** [comment]
Broken is a strong word, they just do not have wide/big versions.

**Comment by khaledhosny** [comment]
Please show some example ( screenshots) of the too wide `\widehat`.

**Comment by khaledhosny** [comment]
I can’t reproduce the `\widehat` issue with XeTeX, looks like a LuaTeX bug.

**Comment by musm** [comment]
Compiling the doc with a master copy of this repo produces (lualatex and xelatex)

![image](https://user-images.githubusercontent.com/4319522/28040707-a4f66bc0-6594-11e7-8926-9c5099c2c322.png)

**Comment by khaledhosny** [comment]
Is this the LuaTeX or XeTeX output or they are identical? Can anyone test with Microsoft Word?

**Comment by musm** [comment]
Tested under both LuaTex and XeTeX (output identical)

**Comment by musm** [comment]
@khaledhosny random  characters with word

![image](https://user-images.githubusercontent.com/4319522/28043125-75280e58-659e-11e7-81ce-62724759d557.png)

**Comment by khaledhosny** [comment]
Funnily I can’t process the doc with either XeTeX or LuaTeX, both are failing to produce PDF for me 😃  But I think I know what is broken in the font.

**Comment by musm** [comment]
Great thanks BTW I finally found  a math font that is free and doesn't look terrible so big kudos and looking forward to bug fixes!

**Comment by khaledhosny** [comment]
I managed to fix the issues preventing me from processing the doc with LuaTeX and XeTeX, I still can’t reproduce the issue with XeTeX. Probably XeTeX just aborted with you (as it did with me) and the PDF you had was the one from the LuaTeX run.

**Comment by musm** [comment]
>  Probably XeTeX just aborted with you (as it did with me) and the PDF you had was the one from the LuaTeX run.

...right, I should've caught that. sorry for that

**Comment by khaledhosny** [comment]
Should be fixed now.
