### ISSUE TITLE
Slashed zero missing in math script

### ISSUE THREAD

**Issue by Bromskloss** [khaledhosny/libertinus#82]
I'm trying to use slashed zeroes in LaTeX:

    \documentclass{memoir}
    
    \usepackage{fontspec}
    \usepackage{unicode-math}

    \setmainfont[Numbers=SlashedZero]{Libertinus Serif}
    \setmathfont[Numbers=SlashedZero]{Libertinus Math}
    
    \begin{document}
    Text: 0
    
    Math: $0$
    \end{document}

Compiling (with `lualatex`), I get [slashes only in text mode](https://a.doko.moe/fvkztn.png), and I also get the following warning:

    *************************************************
    * fontspec warning: "icu-feature-not-exist-in-font"
    * 
    * OpenType feature 'Numbers=SlashedZero' (zero) not available for font
    * 'LibertinusMath' with script 'Math' and language 'Default'.
    *************************************************

(I've also tried using Libertinus Serif as the math font, but the outcome is the same.)

Inspecting the font files, there indeed seems to be no "zero" feature in the "math" script:

```
$ otfinfo --font-version libertinusmath-regular.otf 
Version 6.5 
$ otfinfo --features --script=math libertinusmath-regular.otf
ssty	<unknown feature>
$ otfinfo --features --script=latn libertinusmath-regular.otf
calt	Contextual Alternates
ccmp	Glyph Composition/Decomposition
kern	Kerning
liga	Standard Ligatures
mark	Mark Positioning
mkmk	Mark to Mark Positioning
nalt	Alternate Annotation Forms
ss01	Stylistic Set 1
ss02	Stylistic Set 2
ss03	Stylistic Set 3
ss04	Stylistic Set 4
ss05	Stylistic Set 5
ss06	Stylistic Set 6
zero	Slashed Zero
```

It seems to me like the slashed zero should be available also for mathematics, but I might of course have misunderstood how things are supposed to work.

**Comment by khaledhosny** [comment]
But a slashed zero is not usually used in math, even in some fonts ∅ (empty set) looks like a slashed zero. Do any other math fonts have a slashed zero in math?

**Comment by Bromskloss** [comment]
Hi! Thanks for replying!

> But a slashed zero is not usually used in math

I don't usually see it used in other contexts either, actually. In any case, since a glyph for the slashed zero has already been designed for this font, shouldn't it be in the math script as well, though?

> Do any other math fonts have a slashed zero in math?

I don't know. The availability of a slashed zero is the reason I chose Libertinus. I do need it in both math and text, though.

**Comment by khaledhosny** [comment]
There are tens of features in the font that are not available for math, so I need a stronger reason to just enable this one. I still don’t know what you need a slashed zero in math for.

**Comment by Bromskloss** [comment]
Personally, I need it for an occasion where it has become tradition to write all zeroes with slashes.

When you say it's not needed in mathematics, do you mean that one would instead avoid "O" and similar characters?

What is the reason that this and other features are not available in math mode? Is it because of the work it would take to implement them?

**Comment by khaledhosny** [comment]
I have to enable each feature manually. The fact the feature and the glyphs are present in the math font at all is a historical artifact due to the way it was built.
