### ISSUE TITLE
\symbfsfit not working

### ISSUE THREAD

**Issue by sbadrian** [khaledhosny/libertinus#83]
It seems to me that \symbfsfit is not working properly, with default options $\symbfsfit{A}$ produces the same output as just $A$:

```
\documentclass{article}

\usepackage{fontspec}
\usepackage{unicode-math}
\setmainfont{Libertinus Serif}
\setsansfont{Libertinus Sans}
\setmathfont{Libertinus Math}

\begin{document}
    $\symbfsfit{A}=A$
\end{document}
```

**Comment by khaledhosny** [comment]
The font currently lack bold sans-serif italic (because Linux Biolinum didn’t have such a style). `unicode-math` can load specific ranges from other fonts, as a workaround.

**Comment by khaledhosny** [comment]
Turns out I can auto slant the bold sans-serif alphabet and manually change only a few glyphs.
