### ISSUE TITLE
OldStyleNum on Normal UTF-8

### ISSUE THREAD

**Issue by maieul** [khaledhosny/libertinus#84]
Consider this MWE (with XeLaTeX)

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont[]{Libertinus Serif}

\begin{document}
0123456789
          
\end{document}

```

In the PDF output, the number can be pastebin without problem.

But if you do
`\setmainfont[Numbers=OldStyle]{Libertinus Serif}`

The PDF contains not standard unicode carachters, and the pastebin is not possible (or, at least, you does not get the good characters)

**Comment by khaledhosny** [comment]
Seems to be a XeTeX/dvipdfmx issue (might even be a regression as I’m pretty sure this used to work). The glyphs in the font follows the best practices (are not mapped to PUA, has glyph names the follow AGL for new fonts) and should just work. LuaTeX does not seem to have an issue.

A workaround is to use the new `\XeTeXgenerateactualtext` primitive which should make copying from PDF more robust but with increased file size and text selection issues with some viewers.

**Comment by maieul** [comment]
Ok. Thanks. I didn’t know \XeTeXgenerateactualtext (not documented on XeTeX handbook)
