### ISSUE TITLE
missing liturgical latin characters

### ISSUE THREAD

**Issue by eroux** [khaledhosny/libertinus#85]
migration of [SF issue 323](https://sourceforge.net/p/linuxlibertine/bugs/323/): a few characters are missing for the font to be useable  in liturgical latin:

- œ+combining acute
- Œ+combining acute
- œ+combining acute small caps
- ǽ small caps

**Comment by KrasnayaPloshchad** [comment]
Filling to #41

**Comment by mgavioli** [comment]
I may easily be wrong, but none of these characters are encoded as such in Unicode (unless they are a recent addition to some esoteric plan).

Anyway, as all the 'building blocks' (`AE`, `ae.sc`, `OE`, `oe.sc`, `ae`, `oe`, `COMBINING ACUTE ACCENT`) exist, it should be possible to obtain all of the them with the current font. This is in LibreOffice:

![issue_085_screenshot_01](https://user-images.githubusercontent.com/1420743/36421377-74ed1e38-1638-11e8-9023-6750653b6c46.png)

Now, diacritic placement can be improved (particularly `Œ + combining acute`!) and this is probably the bug?

**Comment by eroux** [comment]
The combinations are not in Unicode as such, indeed. The output (diacritics placement mostly) is the issue

**Comment by eroux** [comment]
thanks a lot!
