### ISSUE TITLE
Missing braces for three lines or more (e.g., in cases)

### ISSUE THREAD

**Issue by ailenus** [khaledhosny/libertinus#87]
Missing opening and closing braces for three lines of text or more, such as in the `cases` environment. A MWE:
```tex
\documentclass[11pt]{article}

\usepackage{polyglossia}
\usepackage{fontspec}
\usepackage{amsmath}
\usepackage{unicode-math}

\setmainlanguage[variant=american]{english}

\setmainfont{Libertinus Serif}
\setsansfont{Libertinus Sans}
\setmonofont{Libertinus Mono}
\setmathfont[AutoFakeBold]{Libertinus Math}

\begin{document}

The absolute value of a real number \(a\) is
\[
    \lvert a\rvert = \begin{cases}
        a & \text{if } a > 0,\\
        0 & \text{if } a = 0,\\
        -a & \text{otherwise}.
    \end{cases}
\]
Meanwhile, the Dirac delta function \(\delta\) is
\[
    \delta(x) = \begin{cases}
        +\infty & \text{if } x = 0,\\
        0 & \text{otherwise}.
    \end{cases}
\]
Notice the different braces.

\end{document}
```
which produces
![different braces](http://i.imgur.com/y1BPrnH.png)

**Comment by khaledhosny** [comment]
I don’t see where exactly the braces are missing.

**Comment by ailenus** [comment]
Ok, I compared it with Computer Modern and it seems indeed this is how it's supposed to look. I originally thought the CM opening brace is being used here, since it looks kind of similar to that indeed, and since it's different from all the other opening braces in Libertinus, which curve inside a little.

Would it be possible for the braces to look curvy in `cases` with three lines or more? It looks a tad inconsistent that three-line braces are upright while smaller braces are curvy imho.

**Comment by khaledhosny** [comment]
The bigger braces are composed of several parts (a fixed middle, top and bottom parts, as well as repeated as necessary connecting parts between them) so that TeX can grow them as needed. This places restrictions of how to design them.
