### ISSUE TITLE
Missing italic Greek letters in math mode

### ISSUE THREAD

**Issue by ailenus** [khaledhosny/libertinus#88]
Missing italic **uppercase** Greek letters in math mode.

Libertinus with XeLaTeX:
![Libertinus with XeLaTeX](https://i.imgur.com/lgEv1fw.png)
Code:
```TeX
\documentclass[12pt]{article}

\usepackage{polyglossia}
\usepackage{fontspec}
\usepackage{amsmath}
\usepackage{unicode-math}

\setmainlanguage[variant=american]{english}

\setmainfont{Libertinus Serif}
\setsansfont{Libertinus Sans}
\setmonofont{Libertinus Mono}
\setmathfont[AutoFakeBold]{Libertinus Math}

\begin{document}

\[
    \varGamma \quad
    \varDelta \quad
    \varTheta \quad
    (\Theta) \quad
    \varLambda \quad
    \varPi \quad
    \varSigma \quad
    \varUpsilon \quad
    \varPhi \quad
    \varPsi \quad
    \varOmega
\]

\end{document}
```

Computer Modern with XeLaTeX:
![Computer Modern with XeLaTeX](https://i.imgur.com/h0mG7pr.png)
Code:
```TeX
\documentclass[12pt]{article}

\usepackage{polyglossia}
\usepackage{fontspec}
\usepackage{amsmath}
\usepackage{unicode-math}

\setmainlanguage[variant=american]{english}

\begin{document}

\[
    \varGamma \quad
    \varDelta \quad
    \varTheta \quad
    (\Theta) \quad
    \varLambda \quad
    \varPi \quad
    \varSigma \quad
    \varUpsilon \quad
    \varPhi \quad
    \varPsi \quad
    \varOmega
\]

\end{document}
```

Computer Modern with pdfLaTeX:
![Computer Modern with pdfLaTeX](https://i.imgur.com/7sKFkkG.png)
Code:
```TeX
\documentclass[12pt]{article}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\usepackage{amsmath}

\begin{document}

\[
    \varGamma \quad
    \varDelta \quad
    \varTheta \quad
    (\Theta) \quad
    \varLambda \quad
    \varPi \quad
    \varSigma \quad
    \varUpsilon \quad
    \varPhi \quad
    \varPsi \quad
    \varOmega
\]

\end{document}
```

As I hope should be clear, the Computer Modern font is used for italic uppercase Greek letters in math mode even with Libertinus Math loaded. Also, XeLaTeX seems to have a bug in its way of processing `\varTheta`, which is not present in pdfLaTeX.

But other than the `\varTheta` bit, I do really hope that Libertinus could support all the other italic uppercase Greek letters in math mode.

Thanks!

**Comment by khaledhosny** [comment]
The symbols are certainly present in the font:
![image](https://user-images.githubusercontent.com/93914/30422519-d9c35be6-9948-11e7-99ca-6f921ae3a4cd.png)

```tex
\documentclass[12pt]{article}

\usepackage[math-style=literal]{unicode-math}

\setmainfont{Libertinus Serif}
\setsansfont{Libertinus Sans}
\setmathfont[AutoFakeBold]{Libertinus Math}

\begin{document}

\[
    𝛤 \quad
    𝛥 \quad
    𝛳 \quad
    (𝛩) \quad
    𝛬 \quad
    𝛱 \quad
    𝛴 \quad
    𝛶 \quad
    𝛷 \quad
    𝛹 \quad
    𝛺
\]

\end{document}
```

In your example the italic symbol end up from Computer Modern Math Italic font (which is a legacy TeX font), so it seems to be a LaTeX package’s bug. The `\var*` defines seems to come from amsmath not unicode-math.
