### ISSUE TITLE
Some problems with italic, bold and bold italic small caps 

### ISSUE THREAD

**Issue by RGB-es** [khaledhosny/libertinus#9]
I'm testing version 6.1 of Libertinus and noticed some problems with the small caps feature. 
As you can see on the screenshot, the Qu ligature is missing on the italic and bold versions while in the bold-italic the "fi" does not change into small caps, remaining as a lower-case ligature. 
I'm using XeTeX (trough LyX)
![libertinus1](https://cloud.githubusercontent.com/assets/7756783/12539668/5bb95c1e-c2f8-11e5-93c2-5d6863e1cf5c.png)

**Comment by khaledhosny** [comment]
Should be fixed now, please test the files from git master.
