### ISSUE TITLE
Historic ligatures

### ISSUE THREAD

**Issue by rig8f** [khaledhosny/libertinus#90]
There are some issues with st and ct ligatures, in serif bold italic: I made these tests with xelatex
![lig-xelatex](https://user-images.githubusercontent.com/16189146/30638230-fbbf7ea8-9dfa-11e7-9c87-bf080775c989.png)

Then I tried with Word, having another different behaviour of the font:
![lig-word](https://user-images.githubusercontent.com/16189146/30638231-fbc89eca-9dfa-11e7-80b6-48359403c636.png)

**Comment by KrasnayaPloshchad** [comment]
Here is my test on LibreOffice Writer 5.4, also tested Libertinus Serif Semibold & Semibold Italic
![default](https://user-images.githubusercontent.com/10364351/30651524-8ad75216-9e58-11e7-8bb2-671a599d20bf.png)

**Comment by mgavioli** [comment]
Summary of current situation:

in Regular: both `c_t` and `s_t` belong to the "hlig" feature
in Semibold italic: the `c t ligature` is misnamed `V.alt`and belongs to no feature; `s_t` belongs to the "dlig" feature
in Bold italic: `c_t` belongs to the "hlig" feature and the `s t ligature` is missing!

Assuming the Regular style is correct, fixing the other two should be relatively straightforward.

**Comment by khaledhosny** [comment]
Yes, I think what is in Regular is desired setup.
