### ISSUE TITLE
New multilingual sample file

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/libertinus#94]
This is my rework based on original [Multilingual.pdf](http://www.linuxlibertine.org/fileadmin/user_upload/PDF/Multilingual.pdf), including the following requests for corrections:
https://sourceforge.net/p/linuxlibertine/bugs/88/
https://sourceforge.net/p/linuxlibertine/bugs/263/
Is it possible to submit into documentation path?
[Multilingual.zip](https://github.com/khaledhosny/libertinus/files/1318722/Multilingual.zip)

**Comment by khaledhosny** [comment]
Can you also attach the source file?

**Comment by KrasnayaPloshchad** [comment]
Yes, here is my source file, this requires LO 5.3 or later.
[Multilingual.zip](https://github.com/khaledhosny/libertinus/files/1427856/Multilingual.zip)

**Comment by khaledhosny** [comment]
Thanks!
